#NOI18N
BandSplash.foreground=0, 0, 0
#NOI18N
BandSplash.background=255, 255, 255
jButton1.text=I Agree
jButton2.text=No Thanks
#NOI18N
jPanel1.background=163,204,237
iAgreeClick.Action.text=
iAgreeClick.Action.shortDescription=
noThanksClick.Action.text=
noThanksClick.Action.shortDescription=
IAgreeClick.Action.text=
IAgreeClick.Action.shortDescription=
NoThanksClick.Action.text=
NoThanksClick.Action.shortDescription=
#NOI18N
jButton1.background=101, 175, 217
#NOI18N
jButton2.background=101, 175, 217
jLabel2.text=By clicking, you agree that you will:
jLabel3.text=1. Abide by the terms of the GPL version 2 that this is licensed under
jLabel4.text=2. Cite this program if you find it useful in your research
jLabel6.text=Multi-Dielectric Energy Band Diagram Program
#NOI18N
jLabel6.foreground=5,59,128
jLabel5.text=Richard G. Southwick III, Aaron Sup, Amit Jain,
jLabel7.text=William Knowlton, Michael Baker, Madi Thompson
jLabel8.text=Richard Southwick III and William B. Knowlton. "Stacked Dual Oxide MOS Energy Band Diagram Visual
jLabel9.text=Representation Program (IRW Student Paper)." IEEE Transactions on Device and Materials Reliability.
jLabel10.text=(2006) Vol. 6, No. 2, pp 136-145
jLabel1.text=
#NOI18N
jLabel1.icon=BandIcon.png
jLabel11.text=R.G. Southwick III, A. Sup, A. Jain, and W.B. Knowlton, "An Interactive Simulation Tool for Complex
jLabel12.text=Multilayer Dielectic Devices", IEEE Transactions on Device and Materials Reliability (2011), Vol. 11,
jLabel13.text=No. 2, pp 236-243
jLabel14.text=
#NOI18N
jLabel14.icon=bandsplash.png
BSULabel.text=
#NOI18N
BSULabel.icon=boisestate-primarylogo-2color-rgb-scaled_down.png
