/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BandDielectric.java
 *
 * Created on Jan 20, 2010, 8:46:20 PM
 */

package band;

import java.awt.*;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.beans.PropertyChangeListener;
import java.beans.PropertyChangeSupport;
import java.util.*;
import javax.swing.*;
import javax.swing.AbstractAction;
import javax.swing.GroupLayout;
import javax.swing.InputMap;
import javax.swing.JColorChooser;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import javax.swing.LayoutStyle;
//import org.jdesktop.application.Action;
import org.jdesktop.beansbinding.*;
import org.jdesktop.beansbinding.AutoBinding.UpdateStrategy;

/**
 *
 * @author mbaker
 */
public class BandMaterialMetal extends MaterialSelect {

   private Metal currentRecord;
   private boolean confirmed;

    /** Creates new form BandDielectric */
    public BandMaterialMetal(java.awt.Frame parent, boolean modal) {
        super(parent, modal);

        InputMap iMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        iMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), "escape");
        iMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0), "enter");

        getRootPane().getActionMap().put("escape", new AbstractAction() {
           @Override
           public void actionPerformed(ActionEvent e) {
              jButtonCancel_Click();
           }
        });

        getRootPane().getActionMap().put("enter", new AbstractAction() {
           @Override
           public void actionPerformed(ActionEvent e) {
              jButtonOK_Click();
           }
        });

        setConfirmed(false);
        getRootPane().setDefaultButton(jButtonOK);
        
        initComponents();

        addWindowListener( new WindowAdapter() {
           @Override
           public void windowOpened(WindowEvent e) {
              jTextFieldThickness.requestFocusInWindow();
              jTextFieldThickness.selectAll();
           }
        });
    }
    
    @Override
    public void setCurrentRecord(Material m) {
       Metal oldMetal = currentRecord;
       currentRecord = (Metal) m;
       propertyChangeSupport.firePropertyChange("currentRecord", oldMetal, currentRecord);
    }

    @Override
    public Metal getCurrentRecord() {
       return currentRecord;
    }

//    @Action
    public void jButtonOK_Click() {
       if (jTextFieldName.getText().isEmpty()) {
          JOptionPane.showMessageDialog(this, "Name is a required field.");
          jTextFieldName.requestFocus();
          return;
       }
       if (jTextFieldWorkFunction.getText().isEmpty()) {
          JOptionPane.showMessageDialog(this, "Work Function is a required field.");
          jTextFieldWorkFunction.requestFocus();
          return;
       }
       if (jTextFieldCharge.getText().isEmpty()) {
          JOptionPane.showMessageDialog(this, "Charge is a required field.");
          jTextFieldCharge.requestFocus();
          return;
       }
       if (jTextFieldThickness.getText().isEmpty()) {
          JOptionPane.showMessageDialog(this, "Thickness is a required field.");
          jTextFieldThickness.requestFocus();
          return;
       }
       if (currentRecord.getThickness() > 0) {
          setConfirmed(true);
          setVisible(false);
       }
       else {
          JOptionPane.showMessageDialog(rootPane, "The thickness must be bigger than 0!");
       }
    }

//    @Action
    public void jButtonCancel_Click() {
       setConfirmed(false);
       setVisible(false);
    }

    @Override
    public boolean isConfirmed() {
       return confirmed;
    }

    @Override
    public void setConfirmed(boolean value) {
       confirmed = value;
    }

//    @Action
    public void showColorChooser() {
       Color newColor = JColorChooser.showDialog(rootPane, "Choose a color...", jPanelPlotColor.getBackground());
       if (newColor != null) {
          jPanelPlotColor.setBackground(newColor);
       }
    }

    private PropertyChangeSupport propertyChangeSupport = new PropertyChangeSupport(this);

    /**
    * Add PropertyChangeListener.
    *
    * @param listener
    */
   @Override
   public void addPropertyChangeListener(PropertyChangeListener listener) {
      propertyChangeSupport.addPropertyChangeListener(listener);
   }

   /**
    * Remove PropertyChangeListener.
    *
    * @param listener
    */
   @Override
   public void removePropertyChangeListener(PropertyChangeListener listener) {
      propertyChangeSupport.removePropertyChangeListener(listener);
   }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    // Generated using JFormDesigner Educational license - Madi Thompson (madithompson)
    private void initComponents() {
	ResourceBundle bundle = ResourceBundle.getBundle("band.resources.BandMaterialMetal");
	jButtonOK = new JButton();
	jButtonCancel = new JButton();
	jLabelName = new JLabel();
	jTextFieldName = new JTextField();
	jLabelWorkFunction = new JLabel();
	jTextFieldWorkFunction = new JTextField();
	jButtonPlotColor = new JButton();
	jLabelCharge = new JLabel();
	jTextFieldCharge = new JTextField();
	jLabelThickness = new JLabel();
	jTextFieldThickness = new JTextField();
	jLabelNotes = new JLabel();
	jScrollPane1 = new JScrollPane();
	jTextAreaNotes = new JTextArea();
	jPanelPlotColor = new Panel();

	//======== this ========
	setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
	setTitle(bundle.getString("BandMaterialMetal.title"));
	setName("BandMaterialMetal");
	setResizable(false);
	var contentPane = getContentPane();

	//---- jButtonOK ----
	jButtonOK.setText(bundle.getString("jButtonOK.text"));
	jButtonOK.setName("jButtonOK");

	//---- jButtonCancel ----
	jButtonCancel.setText(bundle.getString("jButtonCancel.text"));
	jButtonCancel.setName("jButtonCancel");

	//---- jLabelName ----
	jLabelName.setText(bundle.getString("jLabelName.text"));
	jLabelName.setName("jLabelName");

	//---- jTextFieldName ----
	jTextFieldName.setName("jTextFieldName");

	//---- jLabelWorkFunction ----
	jLabelWorkFunction.setText(bundle.getString("jLabelWorkFunction.text"));
	jLabelWorkFunction.setName("jLabelWorkFunction");

	//---- jTextFieldWorkFunction ----
	jTextFieldWorkFunction.setName("jTextFieldWorkFunction");

	//---- jButtonPlotColor ----
	jButtonPlotColor.setText(bundle.getString("jButtonPlotColor.text"));
	jButtonPlotColor.setActionCommand(bundle.getString("jButtonPlotColor.actionCommand"));
	jButtonPlotColor.setName("jButtonPlotColor");

	//---- jLabelCharge ----
	jLabelCharge.setText(bundle.getString("jLabelCharge.text"));
	jLabelCharge.setName("jLabelCharge");

	//---- jTextFieldCharge ----
	jTextFieldCharge.setName("jTextFieldCharge");

	//---- jLabelThickness ----
	jLabelThickness.setText(bundle.getString("jLabelThickness.text"));
	jLabelThickness.setName("jLabelThickness");

	//---- jTextFieldThickness ----
	jTextFieldThickness.setName("jTextFieldThickness");

	//---- jLabelNotes ----
	jLabelNotes.setText(bundle.getString("jLabelNotes.text"));
	jLabelNotes.setName("jLabelNotes");

	//======== jScrollPane1 ========
	{
	    jScrollPane1.setName("jScrollPane1");

	    //---- jTextAreaNotes ----
	    jTextAreaNotes.setColumns(20);
	    jTextAreaNotes.setLineWrap(true);
	    jTextAreaNotes.setRows(5);
	    jTextAreaNotes.setWrapStyleWord(true);
	    jTextAreaNotes.setName("jTextAreaNotes");
	    jScrollPane1.setViewportView(jTextAreaNotes);
	}

	//======== jPanelPlotColor ========
	{
	    jPanelPlotColor.setName("jPanelPlotColor");

	    GroupLayout jPanelPlotColorLayout = new GroupLayout(jPanelPlotColor);
	    jPanelPlotColor.setLayout(jPanelPlotColorLayout);
	    jPanelPlotColorLayout.setHorizontalGroup(
		jPanelPlotColorLayout.createParallelGroup()
		    .addGap(0, 53, Short.MAX_VALUE)
	    );
	    jPanelPlotColorLayout.setVerticalGroup(
		jPanelPlotColorLayout.createParallelGroup()
		    .addGap(0, 23, Short.MAX_VALUE)
	    );
	}

	GroupLayout contentPaneLayout = new GroupLayout(contentPane);
	contentPane.setLayout(contentPaneLayout);
	contentPaneLayout.setHorizontalGroup(
	    contentPaneLayout.createParallelGroup()
		.addGroup(contentPaneLayout.createSequentialGroup()
		    .addContainerGap()
		    .addGroup(contentPaneLayout.createParallelGroup()
			.addGroup(contentPaneLayout.createSequentialGroup()
			    .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
			    .addContainerGap())
			.addGroup(contentPaneLayout.createSequentialGroup()
			    .addGroup(contentPaneLayout.createParallelGroup()
				.addGroup(contentPaneLayout.createSequentialGroup()
				    .addComponent(jButtonOK, GroupLayout.PREFERRED_SIZE, 72, GroupLayout.PREFERRED_SIZE)
				    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
				    .addComponent(jButtonCancel)
				    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
				    .addComponent(jButtonPlotColor)
				    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
				    .addComponent(jPanelPlotColor, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
				.addComponent(jLabelNotes)
				.addGroup(contentPaneLayout.createSequentialGroup()
				    .addComponent(jLabelName)
				    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
				    .addComponent(jTextFieldName, GroupLayout.PREFERRED_SIZE, 93, GroupLayout.PREFERRED_SIZE)
				    .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
				    .addComponent(jLabelWorkFunction)
				    .addGap(17, 17, 17)
				    .addComponent(jTextFieldWorkFunction, GroupLayout.PREFERRED_SIZE, 152, GroupLayout.PREFERRED_SIZE)))
			    .addGap(4, 4, 4)
			    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
				.addComponent(jLabelThickness)
				.addComponent(jLabelCharge))
			    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
			    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
				.addComponent(jTextFieldCharge)
				.addComponent(jTextFieldThickness, GroupLayout.PREFERRED_SIZE, 78, GroupLayout.PREFERRED_SIZE)))))
	);
	contentPaneLayout.setVerticalGroup(
	    contentPaneLayout.createParallelGroup()
		.addGroup(contentPaneLayout.createSequentialGroup()
		    .addContainerGap()
		    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
			.addGroup(contentPaneLayout.createSequentialGroup()
			    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
				.addComponent(jPanelPlotColor, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addComponent(jButtonOK, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addComponent(jButtonCancel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addComponent(jButtonPlotColor, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
			    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
			    .addGroup(contentPaneLayout.createParallelGroup()
				.addComponent(jTextFieldName)
				.addComponent(jTextFieldWorkFunction, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
				.addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
				    .addComponent(jLabelName)
				    .addComponent(jLabelWorkFunction))))
			.addGroup(contentPaneLayout.createSequentialGroup()
			    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
				.addComponent(jLabelCharge)
				.addComponent(jTextFieldCharge, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
			    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
			    .addGroup(contentPaneLayout.createParallelGroup()
				.addComponent(jTextFieldThickness, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
				.addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
				    .addComponent(jLabelThickness)))))
		    .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
		    .addComponent(jLabelNotes)
		    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
		    .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
		    .addContainerGap())
	);
	pack();
	setLocationRelativeTo(getOwner());

	//---- bindings ----
	bindingGroup = new BindingGroup();
	bindingGroup.addBinding(Bindings.createAutoBinding(UpdateStrategy.READ_WRITE,
	    this, ELProperty.create("${currentRecord.name}"),
	    jTextFieldName, BeanProperty.create("text")));
	bindingGroup.addBinding(Bindings.createAutoBinding(UpdateStrategy.READ_WRITE,
	    this, ELProperty.create("${currentRecord.workFunction}"),
	    jTextFieldWorkFunction, BeanProperty.create("text")));
	bindingGroup.addBinding(Bindings.createAutoBinding(UpdateStrategy.READ_WRITE,
	    this, ELProperty.create("${currentRecord.extraCharge}"),
	    jTextFieldCharge, BeanProperty.create("text")));
	bindingGroup.addBinding(Bindings.createAutoBinding(UpdateStrategy.READ_WRITE,
	    this, ELProperty.create("${currentRecord.thicknessNm}"),
	    jTextFieldThickness, BeanProperty.create("text")));
	bindingGroup.addBinding(Bindings.createAutoBinding(UpdateStrategy.READ_WRITE,
	    this, ELProperty.create("${currentRecord.notes}"),
	    jTextAreaNotes, BeanProperty.create("text")));
	bindingGroup.addBinding(Bindings.createAutoBinding(UpdateStrategy.READ_WRITE,
	    this, ELProperty.create("${currentRecord.fillColor}"),
	    jPanelPlotColor, BeanProperty.create("background")));
	bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BandMaterialMetal dialog = new BandMaterialMetal(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // Generated using JFormDesigner Educational license - Madi Thompson (madithompson)
    private JButton jButtonOK;
    private JButton jButtonCancel;
    private JLabel jLabelName;
    private JTextField jTextFieldName;
    private JLabel jLabelWorkFunction;
    private JTextField jTextFieldWorkFunction;
    private JButton jButtonPlotColor;
    private JLabel jLabelCharge;
    private JTextField jTextFieldCharge;
    private JLabel jLabelThickness;
    private JTextField jTextFieldThickness;
    private JLabel jLabelNotes;
    private JScrollPane jScrollPane1;
    private JTextArea jTextAreaNotes;
    private Panel jPanelPlotColor;
    private BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
