/*
 * BandMovieParameters.java
 *
 * Created on Jan 21, 2010, 9:22:26 PM
 */
package band;

import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.AbstractAction;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import org.jdesktop.application.Action;
import org.jdesktop.observablecollections.ObservableCollections;
import org.jdesktop.observablecollections.ObservableList;
import org.jfree.chart.ChartPanel;

/**
 *
 * @author mbaker
 */
public class BandMovieParameters extends javax.swing.JDialog {

    /** Creates new form BandMovieParameters */
    public BandMovieParameters(java.awt.Frame parent, boolean modal) {
        super(parent, modal);

        InputMap iMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        iMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0), "enter");

        getRootPane().getActionMap().put("enter", new AbstractAction() {
           @Override
           public void actionPerformed(ActionEvent e) {
              updateValues();
              dispose();
           }
        });

        initComponents();
        getRootPane().setDefaultButton(jButtonOK);

        loadValues();
    }   

    public void updateStepSize() {
       BandApp app = BandApp.getApplication();
       
       updateValues();

       jTextFieldStepSize.setText(String.valueOf((app.getStopVoltage() - app.getStartVoltage()) / app.getNumberOfSteps()));
    }

    @Action
    public void updateValues() {
       BandApp app = BandApp.getApplication();

       try {
          app.setStartVoltage(Double.valueOf(jTextFieldStartVoltage.getText()));
          app.setStopVoltage(Double.valueOf(jTextFieldStopVoltage.getText()));
          app.setNumberOfSteps(Integer.valueOf(jTextFieldNumberOfSteps.getText()));
          app.setSmartScale(jCheckBoxSmartAxisSize.isSelected());
          if (app.isSmartScale()){
              app.setxAutoScale(true);
              app.setyAutoScale(true);
          }
       } catch (Exception e) {}
    }

    private void loadValues() {
       BandApp app = BandApp.getApplication();
       jTextFieldStartVoltage.setText(String.valueOf(app.getStartVoltage()));
       jTextFieldStopVoltage.setText(String.valueOf(app.getStopVoltage()));
       jTextFieldNumberOfSteps.setText(String.valueOf(app.getNumberOfSteps()));
       jTextFieldStepSize.setText(String.valueOf((app.getStopVoltage() - app.getStartVoltage()) / app.getNumberOfSteps()));
       jCheckBoxSmartAxisSize.setSelected(app.isSmartScale());
    }

     @Action
    public void cancelMovieParametersBox() {
       dispose();
    }

    @Action
    public void closeMovieParametersBox() {
       updateValues();
       
       dispose();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelStartVoltage = new javax.swing.JLabel();
        jTextFieldStartVoltage = new javax.swing.JTextField();
        jLabelStopVoltage = new javax.swing.JLabel();
        jTextFieldStopVoltage = new javax.swing.JTextField();
        jLabelNumberOfSteps = new javax.swing.JLabel();
        jTextFieldNumberOfSteps = new javax.swing.JTextField();
        jLabelStepSize = new javax.swing.JLabel();
        jTextFieldStepSize = new javax.swing.JTextField();
        jButtonOK = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jLabelOutputParameters = new javax.swing.JLabel();
        jCheckBoxSmartAxisSize = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(band.BandApp.class).getContext().getResourceMap(BandMovieParameters.class);
        setTitle(resourceMap.getString("BandMovieParameters.title")); // NOI18N
        setName("BandMovieParameters"); // NOI18N
        setResizable(false);

        jLabelStartVoltage.setText(resourceMap.getString("jLabelStartVoltage.text")); // NOI18N
        jLabelStartVoltage.setName("jLabelStartVoltage"); // NOI18N

        jTextFieldStartVoltage.setText(resourceMap.getString("jTextFieldStartVoltage.text")); // NOI18N
        jTextFieldStartVoltage.setName("jTextFieldStartVoltage"); // NOI18N
        jTextFieldStartVoltage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldStartVoltageKeyPressed(evt);
            }
        });

        jLabelStopVoltage.setText(resourceMap.getString("jLabelStopVoltage.text")); // NOI18N
        jLabelStopVoltage.setName("jLabelStopVoltage"); // NOI18N

        jTextFieldStopVoltage.setText(resourceMap.getString("jTextFieldStopVoltage.text")); // NOI18N
        jTextFieldStopVoltage.setName("jTextFieldStopVoltage"); // NOI18N
        jTextFieldStopVoltage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldStopVoltageKeyPressed(evt);
            }
        });

        jLabelNumberOfSteps.setText(resourceMap.getString("jLabelNumberOfSteps.text")); // NOI18N
        jLabelNumberOfSteps.setName("jLabelNumberOfSteps"); // NOI18N

        jTextFieldNumberOfSteps.setText(resourceMap.getString("jTextFieldNumberOfSteps.text")); // NOI18N
        jTextFieldNumberOfSteps.setName("jTextFieldNumberOfSteps"); // NOI18N
        jTextFieldNumberOfSteps.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldNumberOfStepsKeyPressed(evt);
            }
        });

        jLabelStepSize.setText(resourceMap.getString("jLabelStepSize.text")); // NOI18N
        jLabelStepSize.setName("jLabelStepSize"); // NOI18N

        jTextFieldStepSize.setEditable(false);
        jTextFieldStepSize.setText(resourceMap.getString("jTextFieldStepSize.text")); // NOI18N
        jTextFieldStepSize.setName("jTextFieldStepSize"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(band.BandApp.class).getContext().getActionMap(BandMovieParameters.class, this);
        jButtonOK.setAction(actionMap.get("closeMovieParametersBox")); // NOI18N
        jButtonOK.setText(resourceMap.getString("jButtonOK.text")); // NOI18N
        jButtonOK.setActionCommand(resourceMap.getString("jButtonOK.actionCommand")); // NOI18N
        jButtonOK.setName("jButtonOK"); // NOI18N

        jButtonCancel.setAction(actionMap.get("cancelMovieParametersBox")); // NOI18N
        jButtonCancel.setText(resourceMap.getString("jButtonCancel.text")); // NOI18N
        jButtonCancel.setName("jButtonCancel"); // NOI18N

        jLabelOutputParameters.setName("jLabelOutputParameters"); // NOI18N

        jCheckBoxSmartAxisSize.setText(resourceMap.getString("jCheckBoxSmartAxisSize.text")); // NOI18N
        jCheckBoxSmartAxisSize.setName("jCheckBoxSmartAxisSize"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jCheckBoxSmartAxisSize, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(21, 21, 21)
                            .addComponent(jButtonOK)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonCancel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelStopVoltage)
                                    .addComponent(jLabelStartVoltage))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldStopVoltage)
                                    .addComponent(jTextFieldStartVoltage, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelNumberOfSteps)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldNumberOfSteps))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelStepSize)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldStepSize)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabelOutputParameters))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelStartVoltage)
                    .addComponent(jTextFieldStartVoltage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelOutputParameters))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelStopVoltage)
                    .addComponent(jTextFieldStopVoltage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNumberOfSteps)
                    .addComponent(jTextFieldNumberOfSteps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelStepSize)
                    .addComponent(jTextFieldStepSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addComponent(jCheckBoxSmartAxisSize)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonOK)
                    .addComponent(jButtonCancel))
                .addContainerGap())
        );

        jCheckBoxSmartAxisSize.getAccessibleContext().setAccessibleDescription(resourceMap.getString("jCheckBoxSmartAxisSize.AccessibleContext.accessibleDescription")); // NOI18N

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldStartVoltageKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldStartVoltageKeyPressed
       updateStepSize();
    }//GEN-LAST:event_jTextFieldStartVoltageKeyPressed

    private void jTextFieldStopVoltageKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldStopVoltageKeyPressed
       updateStepSize();
    }//GEN-LAST:event_jTextFieldStopVoltageKeyPressed

    private void jTextFieldNumberOfStepsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNumberOfStepsKeyPressed
       updateStepSize();
    }//GEN-LAST:event_jTextFieldNumberOfStepsKeyPressed


    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BandMovieParameters dialog = new BandMovieParameters(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JCheckBox jCheckBoxSmartAxisSize;
    private javax.swing.JLabel jLabelNumberOfSteps;
    private javax.swing.JLabel jLabelOutputParameters;
    private javax.swing.JLabel jLabelStartVoltage;
    private javax.swing.JLabel jLabelStepSize;
    private javax.swing.JLabel jLabelStopVoltage;
    private javax.swing.JTextField jTextFieldNumberOfSteps;
    private javax.swing.JTextField jTextFieldStartVoltage;
    private javax.swing.JTextField jTextFieldStepSize;
    private javax.swing.JTextField jTextFieldStopVoltage;
    // End of variables declaration//GEN-END:variables

}
