/*
 * BandMovieParameters.java
 *
 * Created on Jan 21, 2010, 9:22:26 PM
 */
package band;

import java.awt.event.*;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.util.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.*;
import javax.swing.AbstractAction;
import javax.swing.GroupLayout;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import javax.swing.LayoutStyle;
//import org.jdesktop.application.Action;
import org.jdesktop.observablecollections.ObservableCollections;
import org.jdesktop.observablecollections.ObservableList;
import org.jfree.chart.ChartPanel;

/**
 *
 * @author mbaker
 */
public class BandMovieParameters extends javax.swing.JDialog {

    /** Creates new form BandMovieParameters */
    public BandMovieParameters(java.awt.Frame parent, boolean modal) {
        super(parent, modal);

        InputMap iMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        iMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0), "enter");

        getRootPane().getActionMap().put("enter", new AbstractAction() {
           @Override
           public void actionPerformed(ActionEvent e) {
              updateValues();
              dispose();
           }
        });

        initComponents();
        getRootPane().setDefaultButton(jButtonOK);

        loadValues();
    }   

    public void updateStepSize() {
       BandApp app = BandApp.getApplication();
       
       updateValues();

       jTextFieldStepSize.setText(String.valueOf((app.getStopVoltage() - app.getStartVoltage()) / app.getNumberOfSteps()));
    }

//    @Action
    public void updateValues() {
       BandApp app = BandApp.getApplication();

       try {
          app.setStartVoltage(Double.valueOf(jTextFieldStartVoltage.getText()));
          app.setStopVoltage(Double.valueOf(jTextFieldStopVoltage.getText()));
          app.setNumberOfSteps(Integer.valueOf(jTextFieldNumberOfSteps.getText()));
          app.setSmartScale(jCheckBoxSmartAxisSize.isSelected());
          if (app.isSmartScale()){
              app.setxAutoScale(true);
              app.setyAutoScale(true);
          }
       } catch (Exception e) {}
    }

    private void loadValues() {
       BandApp app = BandApp.getApplication();
       jTextFieldStartVoltage.setText(String.valueOf(app.getStartVoltage()));
       jTextFieldStopVoltage.setText(String.valueOf(app.getStopVoltage()));
       jTextFieldNumberOfSteps.setText(String.valueOf(app.getNumberOfSteps()));
       jTextFieldStepSize.setText(String.valueOf((app.getStopVoltage() - app.getStartVoltage()) / app.getNumberOfSteps()));
       jCheckBoxSmartAxisSize.setSelected(app.isSmartScale());
    }

//     @Action
    public void cancelMovieParametersBox() {
       dispose();
    }

//    @Action
    public void closeMovieParametersBox() {
       updateValues();
       
       dispose();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    // Generated using JFormDesigner Educational license - Madi Thompson (madithompson)
    private void initComponents() {
	ResourceBundle bundle = ResourceBundle.getBundle("band.resources.BandMovieParameters");
	jLabelStartVoltage = new JLabel();
	jTextFieldStartVoltage = new JTextField();
	jLabelStopVoltage = new JLabel();
	jTextFieldStopVoltage = new JTextField();
	jLabelNumberOfSteps = new JLabel();
	jTextFieldNumberOfSteps = new JTextField();
	jLabelStepSize = new JLabel();
	jTextFieldStepSize = new JTextField();
	jButtonOK = new JButton();
	jButtonCancel = new JButton();
	jLabelOutputParameters = new JLabel();
	jCheckBoxSmartAxisSize = new JCheckBox();

	//======== this ========
	setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
	setTitle(bundle.getString("BandMovieParameters.title"));
	setName("BandMovieParameters");
	setResizable(false);
	var contentPane = getContentPane();

	//---- jLabelStartVoltage ----
	jLabelStartVoltage.setText(bundle.getString("jLabelStartVoltage.text"));
	jLabelStartVoltage.setName("jLabelStartVoltage");

	//---- jTextFieldStartVoltage ----
	jTextFieldStartVoltage.setText(bundle.getString("jTextFieldStartVoltage.text"));
	jTextFieldStartVoltage.setName("jTextFieldStartVoltage");
	jTextFieldStartVoltage.addKeyListener(new KeyAdapter() {
	    @Override
	    public void keyPressed(KeyEvent e) {
		jTextFieldStartVoltageKeyPressed(e);
	    }
	});

	//---- jLabelStopVoltage ----
	jLabelStopVoltage.setText(bundle.getString("jLabelStopVoltage.text"));
	jLabelStopVoltage.setName("jLabelStopVoltage");

	//---- jTextFieldStopVoltage ----
	jTextFieldStopVoltage.setText(bundle.getString("jTextFieldStopVoltage.text"));
	jTextFieldStopVoltage.setName("jTextFieldStopVoltage");
	jTextFieldStopVoltage.addKeyListener(new KeyAdapter() {
	    @Override
	    public void keyPressed(KeyEvent e) {
		jTextFieldStopVoltageKeyPressed(e);
	    }
	});

	//---- jLabelNumberOfSteps ----
	jLabelNumberOfSteps.setText(bundle.getString("jLabelNumberOfSteps.text"));
	jLabelNumberOfSteps.setName("jLabelNumberOfSteps");

	//---- jTextFieldNumberOfSteps ----
	jTextFieldNumberOfSteps.setText(bundle.getString("jTextFieldNumberOfSteps.text"));
	jTextFieldNumberOfSteps.setName("jTextFieldNumberOfSteps");
	jTextFieldNumberOfSteps.addKeyListener(new KeyAdapter() {
	    @Override
	    public void keyPressed(KeyEvent e) {
		jTextFieldNumberOfStepsKeyPressed(e);
	    }
	});

	//---- jLabelStepSize ----
	jLabelStepSize.setText(bundle.getString("jLabelStepSize.text"));
	jLabelStepSize.setName("jLabelStepSize");

	//---- jTextFieldStepSize ----
	jTextFieldStepSize.setEditable(false);
	jTextFieldStepSize.setText(bundle.getString("jTextFieldStepSize.text"));
	jTextFieldStepSize.setName("jTextFieldStepSize");

	//---- jButtonOK ----
	jButtonOK.setText(bundle.getString("jButtonOK.text"));
	jButtonOK.setActionCommand(bundle.getString("jButtonOK.actionCommand"));
	jButtonOK.setName("jButtonOK");

	//---- jButtonCancel ----
	jButtonCancel.setText(bundle.getString("jButtonCancel.text"));
	jButtonCancel.setName("jButtonCancel");

	//---- jLabelOutputParameters ----
	jLabelOutputParameters.setName("jLabelOutputParameters");

	//---- jCheckBoxSmartAxisSize ----
	jCheckBoxSmartAxisSize.setText(bundle.getString("jCheckBoxSmartAxisSize.text"));
	jCheckBoxSmartAxisSize.setName("jCheckBoxSmartAxisSize");

	GroupLayout contentPaneLayout = new GroupLayout(contentPane);
	contentPane.setLayout(contentPaneLayout);
	contentPaneLayout.setHorizontalGroup(
	    contentPaneLayout.createParallelGroup()
		.addGroup(contentPaneLayout.createSequentialGroup()
		    .addContainerGap()
		    .addGroup(contentPaneLayout.createParallelGroup()
			.addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
			    .addComponent(jCheckBoxSmartAxisSize, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
			    .addGroup(GroupLayout.Alignment.LEADING, contentPaneLayout.createSequentialGroup()
				.addGap(21, 21, 21)
				.addComponent(jButtonOK)
				.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
				.addComponent(jButtonCancel)))
			.addGroup(contentPaneLayout.createSequentialGroup()
			    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
				.addGroup(contentPaneLayout.createSequentialGroup()
				    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
					.addComponent(jLabelStopVoltage)
					.addComponent(jLabelStartVoltage))
				    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
				    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
					.addComponent(jTextFieldStopVoltage)
					.addComponent(jTextFieldStartVoltage, GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)))
				.addGroup(contentPaneLayout.createSequentialGroup()
				    .addComponent(jLabelNumberOfSteps)
				    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
				    .addComponent(jTextFieldNumberOfSteps))
				.addGroup(contentPaneLayout.createSequentialGroup()
				    .addComponent(jLabelStepSize)
				    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
				    .addComponent(jTextFieldStepSize)))
			    .addGap(18, 18, 18)
			    .addComponent(jLabelOutputParameters))))
	);
	contentPaneLayout.setVerticalGroup(
	    contentPaneLayout.createParallelGroup()
		.addGroup(contentPaneLayout.createSequentialGroup()
		    .addContainerGap()
		    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
			.addComponent(jLabelStartVoltage)
			.addComponent(jTextFieldStartVoltage, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
			.addComponent(jLabelOutputParameters))
		    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
		    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
			.addComponent(jLabelStopVoltage)
			.addComponent(jTextFieldStopVoltage, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
		    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
		    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
			.addComponent(jLabelNumberOfSteps)
			.addComponent(jTextFieldNumberOfSteps, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
		    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
		    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
			.addComponent(jLabelStepSize)
			.addComponent(jTextFieldStepSize, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
		    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
		    .addComponent(jCheckBoxSmartAxisSize)
		    .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
		    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
			.addComponent(jButtonOK)
			.addComponent(jButtonCancel))
		    .addContainerGap())
	);
	pack();
	setLocationRelativeTo(getOwner());
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldStartVoltageKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldStartVoltageKeyPressed
       updateStepSize();
    }//GEN-LAST:event_jTextFieldStartVoltageKeyPressed

    private void jTextFieldStopVoltageKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldStopVoltageKeyPressed
       updateStepSize();
    }//GEN-LAST:event_jTextFieldStopVoltageKeyPressed

    private void jTextFieldNumberOfStepsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNumberOfStepsKeyPressed
       updateStepSize();
    }//GEN-LAST:event_jTextFieldNumberOfStepsKeyPressed


    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BandMovieParameters dialog = new BandMovieParameters(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // Generated using JFormDesigner Educational license - Madi Thompson (madithompson)
    private JLabel jLabelStartVoltage;
    private JTextField jTextFieldStartVoltage;
    private JLabel jLabelStopVoltage;
    private JTextField jTextFieldStopVoltage;
    private JLabel jLabelNumberOfSteps;
    private JTextField jTextFieldNumberOfSteps;
    private JLabel jLabelStepSize;
    private JTextField jTextFieldStepSize;
    private JButton jButtonOK;
    private JButton jButtonCancel;
    private JLabel jLabelOutputParameters;
    private JCheckBox jCheckBoxSmartAxisSize;
    // End of variables declaration//GEN-END:variables

}
