/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BandViewDielectrics.java
 *
 * Created on Jan 21, 2010, 9:13:51 PM
 */

package band;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import javax.swing.AbstractAction;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import org.jdesktop.application.Action;
import org.jdesktop.observablecollections.ObservableCollections;
import org.jdesktop.observablecollections.ObservableList;

/**
 *
 * @author mbaker
 */
public class BandViewSemiconductors extends javax.swing.JDialog {

   protected ObservableList<Material> listSemiconductor = ObservableCollections.observableList(BandApp.getApplication().getListSemiconductor());
   public static final String PROP_LISTSEMICONDUCTOR = "listSemiconductor";

   public List<Material> getSemiconductors() {
      return listSemiconductor;
   }

   @Action
   public void closeSemiconductorsBox() {
      dispose();
   }

   public void showSemiconductor() {
      BandSemiconductor semiconductorBox = null;
      JFrame mainFrame = BandApp.getApplication().getMainFrame();
      semiconductorBox = new BandSemiconductor(mainFrame,true);
      semiconductorBox.setLocationRelativeTo(semiconductorBox);
   }


    /** Creates new form BandViewDielectrics */
    public BandViewSemiconductors(java.awt.Frame parent, boolean modal) {
        super(parent, modal);

        InputMap iMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        iMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), "escape");
        iMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0), "enter");

        getRootPane().getActionMap().put("escape", new AbstractAction() {
           @Override
           public void actionPerformed(ActionEvent e) {
              dispose();
           }
        });

        getRootPane().getActionMap().put("enter", new AbstractAction() {
           @Override
           public void actionPerformed(ActionEvent e) {
              dispose();
           }
        });

        initComponents();
    }

   

     @Action
    public void newRecord() {
       BandSemiconductor semiconductorBox = null;
       Semiconductor newSemiconductor = new Semiconductor();
       newSemiconductor.fillColor = Color.BLACK;

       JFrame mainFrame = BandApp.getApplication().getMainFrame();
       semiconductorBox = new BandSemiconductor(mainFrame,true);
       semiconductorBox.setLocationRelativeTo(this);
       semiconductorBox.setCurrentRecord(newSemiconductor);
       semiconductorBox.setVisible(true);

       if (semiconductorBox.isConfirmed()) {
          listSemiconductor.add(newSemiconductor);
       }
       
       Collections.sort(listSemiconductor);
    }

    @Action
    public void editRecord() {
       int selectedRow = jTableSemiconductors.getSelectedRow();

       BandSemiconductor semiconductorBox = null;

       JFrame mainFrame = BandApp.getApplication().getMainFrame();
       semiconductorBox = new BandSemiconductor(mainFrame,true);
       semiconductorBox.setLocationRelativeTo(this);
       Semiconductor tempSemiconductor = (Semiconductor)listSemiconductor.get(selectedRow);
       semiconductorBox.setCurrentRecord((Semiconductor)listSemiconductor.get(selectedRow));
       semiconductorBox.setVisible(true);

       if (!semiconductorBox.isConfirmed()) {
          listSemiconductor.remove(selectedRow);
          listSemiconductor.add(selectedRow, tempSemiconductor);
       }
       
       Collections.sort(listSemiconductor);
    }

    @Action
    public void deleteRecord() {
        int n = JOptionPane.showConfirmDialog(null, "Delete the records permanently?", "Warning",
                JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE, null);
        if (n == JOptionPane.YES_OPTION) {
            int[] selected = jTableSemiconductors.getSelectedRows();
            List<Semiconductor> toRemove = new ArrayList<Semiconductor>(selected.length);
            for (int idx = 0; idx < selected.length; idx++) {
                Semiconductor g = (Semiconductor)listSemiconductor.get(jTableSemiconductors.convertRowIndexToModel(selected[idx]));
                toRemove.add(g);
            }
            listSemiconductor.removeAll(toRemove);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {
      bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

      jButtonAdd = new javax.swing.JButton();
      jButtonEdit = new javax.swing.JButton();
      jButtonDelete = new javax.swing.JButton();
      jButtonClose = new javax.swing.JButton();
      jScrollPane1 = new javax.swing.JScrollPane();
      jTableSemiconductors = new javax.swing.JTable();

      setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
      org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(band.BandApp.class).getContext().getResourceMap(BandViewSemiconductors.class);
      setTitle(resourceMap.getString("BandViewSemiconductors.title")); // NOI18N
      setName("BandViewSemiconductors"); // NOI18N

      javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(band.BandApp.class).getContext().getActionMap(BandViewSemiconductors.class, this);
      jButtonAdd.setAction(actionMap.get("newRecord")); // NOI18N
      jButtonAdd.setText(resourceMap.getString("jButtonAdd.text")); // NOI18N
      jButtonAdd.setName("jButtonAdd"); // NOI18N

      jButtonEdit.setAction(actionMap.get("editRecord")); // NOI18N
      jButtonEdit.setText(resourceMap.getString("jButtonEdit.text")); // NOI18N
      jButtonEdit.setName("jButtonEdit"); // NOI18N

      jButtonDelete.setAction(actionMap.get("deleteRecord")); // NOI18N
      jButtonDelete.setText(resourceMap.getString("jButtonDelete.text")); // NOI18N
      jButtonDelete.setName("jButtonDelete"); // NOI18N

      jButtonClose.setAction(actionMap.get("closeSemiconductorsBox")); // NOI18N
      jButtonClose.setText(resourceMap.getString("jButtonClose.text")); // NOI18N
      jButtonClose.setName("jButtonClose"); // NOI18N

      jScrollPane1.setName("jScrollPane1"); // NOI18N

      jTableSemiconductors.setName("jTableSemiconductors"); // NOI18N

      org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${semiconductors}");
      org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, jTableSemiconductors);
      org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${name}"));
      columnBinding.setColumnName("Name");
      columnBinding.setColumnClass(String.class);
      columnBinding.setEditable(false);
      columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${bandGap}"));
      columnBinding.setColumnName("Band Gap");
      columnBinding.setColumnClass(Double.class);
      columnBinding.setEditable(false);
      columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${electronAffinity}"));
      columnBinding.setColumnName("Electron Affinity");
      columnBinding.setColumnClass(Double.class);
      columnBinding.setEditable(false);
      columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${dielectricConstant}"));
      columnBinding.setColumnName("Dielectric Constant");
      columnBinding.setColumnClass(Double.class);
      columnBinding.setEditable(false);
      columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${notes}"));
      columnBinding.setColumnName("Notes");
      columnBinding.setColumnClass(String.class);
      columnBinding.setEditable(false);
      bindingGroup.addBinding(jTableBinding);
      jTableBinding.bind();
      jTableSemiconductors.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseClicked(java.awt.event.MouseEvent evt) {
            jTableSemiconductorsMouseClicked(evt);
         }
      });
      jScrollPane1.setViewportView(jTableSemiconductors);
      jTableSemiconductors.getColumnModel().getColumn(0).setHeaderValue(resourceMap.getString("jTableSemiconductors.columnModel.title0")); // NOI18N
      jTableSemiconductors.getColumnModel().getColumn(1).setHeaderValue(resourceMap.getString("jTableSemiconductors.columnModel.title1")); // NOI18N
      jTableSemiconductors.getColumnModel().getColumn(2).setHeaderValue(resourceMap.getString("jTableSemiconductors.columnModel.title2")); // NOI18N
      jTableSemiconductors.getColumnModel().getColumn(3).setHeaderValue(resourceMap.getString("jTableSemiconductors.columnModel.title3")); // NOI18N
      jTableSemiconductors.getColumnModel().getColumn(4).setHeaderValue(resourceMap.getString("jTableSemiconductors.columnModel.title4")); // NOI18N

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jButtonAdd)
               .addComponent(jButtonEdit)
               .addComponent(jButtonDelete)
               .addComponent(jButtonClose))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
               .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
               .addGroup(layout.createSequentialGroup()
                  .addComponent(jButtonAdd)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(jButtonEdit)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(jButtonDelete)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                  .addComponent(jButtonClose)))
            .addContainerGap())
      );

      bindingGroup.bind();

      pack();
   }// </editor-fold>//GEN-END:initComponents

    private void jTableSemiconductorsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableSemiconductorsMouseClicked
       if (evt.getClickCount() == 2) {
          editRecord();
       }
    }//GEN-LAST:event_jTableSemiconductorsMouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BandViewSemiconductors dialog = new BandViewSemiconductors(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton jButtonAdd;
   private javax.swing.JButton jButtonClose;
   private javax.swing.JButton jButtonDelete;
   private javax.swing.JButton jButtonEdit;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JTable jTableSemiconductors;
   private org.jdesktop.beansbinding.BindingGroup bindingGroup;
   // End of variables declaration//GEN-END:variables
}
