/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BandViewDielectrics.java
 *
 * Created on Jan 21, 2010, 9:13:51 PM
 */

package band;

import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.util.*;
import java.util.List;
import javax.swing.*;
import javax.swing.AbstractAction;
import javax.swing.GroupLayout;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.KeyStroke;
import javax.swing.LayoutStyle;
//import org.jdesktop.application.Action;
import org.jdesktop.beansbinding.*;
import org.jdesktop.beansbinding.AutoBinding.UpdateStrategy;
import org.jdesktop.observablecollections.ObservableCollections;
import org.jdesktop.observablecollections.ObservableList;
import org.jdesktop.swingbinding.*;

/**
 *
 * @author mbaker
 */
public class BandPickMetal extends MaterialPick {

   protected ObservableList<Material> listMetal = ObservableCollections.observableList(BandApp.getApplication().getListMetal());
   public static final String PROP_LISTMETAL = "listMetal";
   private Metal newMetal;
   private boolean confirmed;
   private double thickness = 0;

    /** Creates new form BandViewDielectrics */
    public BandPickMetal(java.awt.Frame parent, boolean modal) {
        super(parent, modal);

        InputMap iMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        iMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), "escape");
        iMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0), "enter");

        getRootPane().getActionMap().put("escape", new AbstractAction() {
           @Override
           public void actionPerformed(ActionEvent e) {
              dispose();
           }
        });

        getRootPane().getActionMap().put("enter", new AbstractAction() {
           @Override
           public void actionPerformed(ActionEvent e) {
              dispose();
           }
        });

        getRootPane().setDefaultButton(jButtonClose);

        confirmed = false;
        
        initComponents();
    }

    public List<Material> getMetals() {
       return listMetal;
    }

//    @Action
    public void closeMetalBox() {
       dispose();
    }

    @Override
    public Material getNewMaterial() {
       return newMetal;
    }
    
    @Override
    public boolean isConfirmed() {
       return confirmed;
    }

    public void setReplace(double thickness) {
        this.thickness = thickness;
        if (thickness > 0) {
           jButtonAdd.setText("Replace");
        }
        else {
            jButtonAdd.setText("Add");
        }
    }

//    @Action
    public void addRecord() {
       int selectedRow = jTableMetals.getSelectedRow();
       newMetal = (Metal)listMetal.get(selectedRow).clone();

       if (thickness > 0) {
           newMetal.setThicknessNm(thickness);
           thickness = 0;
           confirmed = true;
       }
       else {
           JFrame mainFrame = BandApp.getApplication();
           BandMaterialMetal metalBox = new BandMaterialMetal(mainFrame,true);
           metalBox.setCurrentRecord(newMetal);
           metalBox.setVisible(true);

           if (metalBox.isConfirmed()) {
              confirmed = true;
           }
       }

       dispose();       
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    // Generated using JFormDesigner Educational license - Madi Thompson (madithompson)
    private void initComponents() {
	ResourceBundle bundle = ResourceBundle.getBundle("band.resources.BandPickMetal");
	jButtonAdd = new JButton();
	jButtonClose = new JButton();
	jScrollPaneMetals = new JScrollPane();
	jTableMetals = new JTable();

	//======== this ========
	setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
	setTitle(bundle.getString("BandPickMetal.title"));
	setName("BandPickMetal");
	var contentPane = getContentPane();

	//---- jButtonAdd ----
	jButtonAdd.setText(bundle.getString("jButtonAdd.text"));
	jButtonAdd.setName("jButtonAdd");

	//---- jButtonClose ----
	jButtonClose.setText(bundle.getString("jButtonClose.text"));
	jButtonClose.setName("jButtonClose");

	//======== jScrollPaneMetals ========
	{
	    jScrollPaneMetals.setName("jScrollPaneMetals");

	    //---- jTableMetals ----
	    jTableMetals.setName("jTableMetals");
	    jScrollPaneMetals.setViewportView(jTableMetals);
	}

	GroupLayout contentPaneLayout = new GroupLayout(contentPane);
	contentPane.setLayout(contentPaneLayout);
	contentPaneLayout.setHorizontalGroup(
	    contentPaneLayout.createParallelGroup()
		.addGroup(contentPaneLayout.createSequentialGroup()
		    .addContainerGap()
		    .addGroup(contentPaneLayout.createParallelGroup()
			.addComponent(jButtonAdd)
			.addComponent(jButtonClose))
		    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
		    .addComponent(jScrollPaneMetals, GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
		    .addContainerGap())
	);
	contentPaneLayout.setVerticalGroup(
	    contentPaneLayout.createParallelGroup()
		.addGroup(GroupLayout.Alignment.TRAILING, contentPaneLayout.createSequentialGroup()
		    .addContainerGap()
		    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
			.addComponent(jScrollPaneMetals, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
			.addGroup(contentPaneLayout.createSequentialGroup()
			    .addComponent(jButtonAdd)
			    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 181, Short.MAX_VALUE)
			    .addComponent(jButtonClose)))
		    .addContainerGap())
	);
	pack();
	setLocationRelativeTo(getOwner());

	//---- bindings ----
	bindingGroup = new BindingGroup();
	{
	    var binding = SwingBindings.createJTableBinding(UpdateStrategy.READ_WRITE,
		this, (ELProperty) ELProperty.create("${metals}"), jTableMetals);
	    binding.addColumnBinding(ELProperty.create("${name}"))
		.setColumnName("Name")
		.setColumnClass(String.class)
		.setEditable(false);
	    binding.addColumnBinding(ELProperty.create("${workFunction}"))
		.setColumnName("Work Function")
		.setColumnClass(Double.class)
		.setEditable(false);
	    binding.addColumnBinding(ELProperty.create("${notes}"))
		.setColumnName("Notes")
		.setColumnClass(String.class)
		.setEditable(false);
	    bindingGroup.addBinding(binding);
	    binding.bind();
	}
	bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BandPickMetal dialog = new BandPickMetal(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // Generated using JFormDesigner Educational license - Madi Thompson (madithompson)
    private JButton jButtonAdd;
    private JButton jButtonClose;
    private JScrollPane jScrollPaneMetals;
    private JTable jTableMetals;
    private BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

}
