/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BandViewWindow.java
 *
 * Created on Jan 20, 2010, 9:01:40 PM
 */

package band;

import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.util.*;
import javax.swing.*;
import javax.swing.AbstractAction;
import javax.swing.GroupLayout;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JRootPane;
import javax.swing.KeyStroke;
import javax.swing.LayoutStyle;
import org.jdesktop.application.Action;

/**
 *
 * @author mbaker
 */
public class BandViewWindow extends javax.swing.JDialog {

    /** Creates new form BandViewWindow */
    public BandViewWindow(java.awt.Frame parent, boolean modal) {
        super(parent, modal);

        InputMap iMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        iMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), "escape");
        iMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0), "enter");

        getRootPane().getActionMap().put("escape", new AbstractAction() {
           @Override
           public void actionPerformed(ActionEvent e) {
              dispose();
           }
        });

        getRootPane().getActionMap().put("enter", new AbstractAction() {
           @Override
           public void actionPerformed(ActionEvent e) {
              updateValues();
           }
        });

        initComponents();

        JRootPane rp = this.jButtonOk.getRootPane();
        rp.setDefaultButton(jButtonOk);
        
        loadValues();
    }

    @Action
    public void updateValues() {
       BandApp app = BandApp.getApplication();

       app.setxAutoScale(jCheckBoxXAutoScale.isSelected());
       app.setyAutoScale(jCheckBoxYAutoScale.isSelected());

       app.setxMin(Double.valueOf(jTextFieldXMin.getText()));
       app.setxMax(Double.valueOf(jTextFieldXMax.getText()));
       app.setyMin(Double.valueOf(jTextFieldYMin.getText()));
       app.setyMax(Double.valueOf(jTextFieldYMax.getText()));

       if (app.isxAutoScale()) {
          jTextFieldXMin.setEnabled(false);
          jTextFieldXMax.setEnabled(false);
       }
       else {
          jTextFieldXMin.setEnabled(true);
          jTextFieldXMax.setEnabled(true);
       }

       if (app.isyAutoScale()) {
          jTextFieldYMin.setEnabled(false);
          jTextFieldYMax.setEnabled(false);
       }
       else {
          jTextFieldYMin.setEnabled(true);
          jTextFieldYMax.setEnabled(true);
       }
    }

    private void loadValues() {
       BandApp app = BandApp.getApplication();
       jCheckBoxXAutoScale.setSelected(app.isxAutoScale());
       jCheckBoxYAutoScale.setSelected(app.isyAutoScale());

       jTextFieldXMin.setText(String.valueOf(app.getxMin()));
       jTextFieldXMax.setText(String.valueOf(app.getxMax()));
       jTextFieldYMin.setText(String.valueOf(app.getyMin()));
       jTextFieldYMax.setText(String.valueOf(app.getyMax()));
       
       if (app.isxAutoScale()) {
          jTextFieldXMin.setEnabled(false);
          jTextFieldXMax.setEnabled(false);
       }
       else {
          jTextFieldXMin.setEnabled(true);
          jTextFieldXMax.setEnabled(true);
       }

       if (app.isyAutoScale()) {
          jTextFieldYMin.setEnabled(false);
          jTextFieldYMax.setEnabled(false);
       }
       else {
          jTextFieldYMin.setEnabled(true);
          jTextFieldYMax.setEnabled(true);
       }
    }

    @Action
    public void closeWindowBox() {
       updateValues();

       dispose();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   // Generated using JFormDesigner Educational license - Madi Thompson (madithompson)
   private void initComponents() {
       ResourceBundle bundle = ResourceBundle.getBundle("band.resources.BandViewWindow");
       jLabelX = new JLabel();
       jTextFieldXMin = new JTextField();
       jTextFieldXMax = new JTextField();
       jCheckBoxXAutoScale = new JCheckBox();
       jLabelY = new JLabel();
       jTextFieldYMin = new JTextField();
       jTextFieldYMax = new JTextField();
       jCheckBoxYAutoScale = new JCheckBox();
       jButtonOk = new JButton();

       //======== this ========
       setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
       setTitle(bundle.getString("BandViewWindow.title"));
       setModal(true);
       setName("BandViewWindow");
       setResizable(false);
       var contentPane = getContentPane();

       //---- jLabelX ----
       jLabelX.setText(bundle.getString("jLabelX.text"));
       jLabelX.setName("jLabelX");

       //---- jTextFieldXMin ----
       jTextFieldXMin.setText(bundle.getString("jTextFieldXMin.text"));
       jTextFieldXMin.setName("jTextFieldXMin");

       //---- jTextFieldXMax ----
       jTextFieldXMax.setText(bundle.getString("jTextFieldXMax.text"));
       jTextFieldXMax.setName("jTextFieldXMax");

       //---- jCheckBoxXAutoScale ----
       jCheckBoxXAutoScale.setText(bundle.getString("jCheckBoxXAutoScale.text"));
       jCheckBoxXAutoScale.setName("jCheckBoxXAutoScale");

       //---- jLabelY ----
       jLabelY.setText(bundle.getString("jLabelY.text"));
       jLabelY.setName("jLabelY");

       //---- jTextFieldYMin ----
       jTextFieldYMin.setText(bundle.getString("jTextFieldYMin.text"));
       jTextFieldYMin.setName("jTextFieldYMin");

       //---- jTextFieldYMax ----
       jTextFieldYMax.setText(bundle.getString("jTextFieldYMax.text"));
       jTextFieldYMax.setName("jTextFieldYMax");

       //---- jCheckBoxYAutoScale ----
       jCheckBoxYAutoScale.setText(bundle.getString("jCheckBoxYAutoScale.text"));
       jCheckBoxYAutoScale.setName("jCheckBoxYAutoScale");

       //---- jButtonOk ----
       jButtonOk.setText(bundle.getString("jButtonOk.text"));
       jButtonOk.setActionCommand(bundle.getString("jButtonOk.actionCommand"));
       jButtonOk.setName("jButtonOk");

       GroupLayout contentPaneLayout = new GroupLayout(contentPane);
       contentPane.setLayout(contentPaneLayout);
       contentPaneLayout.setHorizontalGroup(
	   contentPaneLayout.createParallelGroup()
	       .addGroup(contentPaneLayout.createSequentialGroup()
		   .addContainerGap()
		   .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
		       .addComponent(jLabelX)
		       .addGroup(contentPaneLayout.createSequentialGroup()
			   .addComponent(jTextFieldXMin, GroupLayout.PREFERRED_SIZE, 99, GroupLayout.PREFERRED_SIZE)
			   .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
			   .addGroup(contentPaneLayout.createParallelGroup()
			       .addComponent(jCheckBoxXAutoScale)
			       .addComponent(jTextFieldXMax, GroupLayout.PREFERRED_SIZE, 101, GroupLayout.PREFERRED_SIZE)))
		       .addGroup(contentPaneLayout.createSequentialGroup()
			   .addGroup(contentPaneLayout.createParallelGroup()
			       .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
				   .addComponent(jTextFieldYMin, GroupLayout.Alignment.LEADING)
				   .addComponent(jLabelY, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
			       .addComponent(jButtonOk, GroupLayout.PREFERRED_SIZE, 77, GroupLayout.PREFERRED_SIZE))
			   .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
			   .addGroup(contentPaneLayout.createParallelGroup()
			       .addComponent(jCheckBoxYAutoScale)
			       .addComponent(jTextFieldYMax))))
		   .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
       );
       contentPaneLayout.setVerticalGroup(
	   contentPaneLayout.createParallelGroup()
	       .addGroup(contentPaneLayout.createSequentialGroup()
		   .addContainerGap()
		   .addComponent(jLabelX)
		   .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
		   .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
		       .addComponent(jTextFieldXMin, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
		       .addComponent(jTextFieldXMax, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
		   .addGroup(contentPaneLayout.createParallelGroup()
		       .addGroup(contentPaneLayout.createSequentialGroup()
			   .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
			   .addComponent(jCheckBoxXAutoScale))
		       .addGroup(contentPaneLayout.createSequentialGroup()
			   .addGap(25, 25, 25)
			   .addComponent(jLabelY)))
		   .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
		   .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
		       .addComponent(jTextFieldYMin, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
		       .addComponent(jTextFieldYMax, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
		   .addGroup(contentPaneLayout.createParallelGroup()
		       .addGroup(contentPaneLayout.createSequentialGroup()
			   .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
			   .addComponent(jCheckBoxYAutoScale))
		       .addGroup(contentPaneLayout.createSequentialGroup()
			   .addGap(22, 22, 22)
			   .addComponent(jButtonOk)))
		   .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
       );
       pack();
       setLocationRelativeTo(getOwner());
   }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BandViewWindow dialog = new BandViewWindow(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   // Generated using JFormDesigner Educational license - Madi Thompson (madithompson)
   private JLabel jLabelX;
   private JTextField jTextFieldXMin;
   private JTextField jTextFieldXMax;
   private JCheckBox jCheckBoxXAutoScale;
   private JLabel jLabelY;
   private JTextField jTextFieldYMin;
   private JTextField jTextFieldYMax;
   private JCheckBox jCheckBoxYAutoScale;
   private JButton jButtonOk;
   // End of variables declaration//GEN-END:variables

}
