/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BandDielectric.java
 *
 * Created on Jan 20, 2010, 8:46:20 PM
 */

package band;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.beans.PropertyChangeListener;
import java.beans.PropertyChangeSupport;
import java.util.*;
import javax.swing.*;
import javax.swing.AbstractAction;
import javax.swing.GroupLayout;
import javax.swing.InputMap;
import javax.swing.JColorChooser;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import javax.swing.LayoutStyle;
//import org.jdesktop.application.Action;
import org.jdesktop.beansbinding.*;
import org.jdesktop.beansbinding.AutoBinding.UpdateStrategy;

/**
 *
 * @author mbaker
 */
public class BandMetal extends javax.swing.JDialog {

   private Metal currentRecord;
   private boolean confirmed;

    /** Creates new form BandDielectric */
    public BandMetal(java.awt.Frame parent, boolean modal) {
        super(parent, modal);

        InputMap iMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        iMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), "escape");
        iMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0), "enter");

        getRootPane().getActionMap().put("escape", new AbstractAction() {
           @Override
           public void actionPerformed(ActionEvent e) {
              jButtonCancel_Click();
           }
        });

        getRootPane().getActionMap().put("enter", new AbstractAction() {
           @Override
           public void actionPerformed(ActionEvent e) {
              jButtonOK_Click();
           }
        });

        setConfirmed(false);
        getRootPane().setDefaultButton(jButtonOK);

        initComponents();
    }

     public void setCurrentRecord(Metal passMetal) {
       Metal oldMetal = currentRecord;
       currentRecord = passMetal;
       propertyChangeSupport.firePropertyChange("currentRecord", oldMetal, currentRecord);
    }

    public Metal getCurrentRecord() {
       return currentRecord;
    }

//    @Action
    public void jButtonOK_Click() {
       if (jTextFieldName.getText().isEmpty()) {
         JOptionPane.showMessageDialog(this, "Name is a required field.");
         jTextFieldName.requestFocus();
         return;
      }
      if (jTextFieldWorkFunction.getText().isEmpty()) {
         JOptionPane.showMessageDialog(this, "Work Function is a required field.");
         jTextFieldWorkFunction.requestFocus();
         return;
      }
        
       setConfirmed(true);
       this.setVisible(false);
    }

//    @Action
    public void jButtonCancel_Click() {
       setConfirmed(false);
       this.setVisible(false);
    }

    public boolean isConfirmed() {
       return confirmed;
    }

    public void setConfirmed(boolean value) {
       confirmed = value;
    }

//    @Action
    public void showColorChooser() {
       Color newColor = JColorChooser.showDialog(rootPane, "Choose a color...", Color.yellow);
       if (newColor != null) {
          jPanelPlotColor.setBackground(newColor);
       }
    }

    private PropertyChangeSupport propertyChangeSupport = new PropertyChangeSupport(this);

    /**
    * Add PropertyChangeListener.
    *
    * @param listener
    */
   @Override
   public void addPropertyChangeListener(PropertyChangeListener listener) {
      propertyChangeSupport.addPropertyChangeListener(listener);
   }

   /**
    * Remove PropertyChangeListener.
    *
    * @param listener
    */
   @Override
   public void removePropertyChangeListener(PropertyChangeListener listener) {
      propertyChangeSupport.removePropertyChangeListener(listener);
   }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    // Generated using JFormDesigner Educational license - Madi Thompson (madithompson)
    private void initComponents() {
	ResourceBundle bundle = ResourceBundle.getBundle("band.resources.BandMetal");
	jButtonOK = new JButton();
	jButtonCancel = new JButton();
	jLabelName = new JLabel();
	jTextFieldName = new JTextField();
	jLabelWorkFunction = new JLabel();
	jTextFieldWorkFunction = new JTextField();
	jButtonPlotColor = new JButton();
	jLabelNotes = new JLabel();
	jScrollPane1 = new JScrollPane();
	jTextAreaNotes = new JTextArea();
	jPanelPlotColor = new JPanel();

	//======== this ========
	setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
	setTitle(bundle.getString("BandMetal.title"));
	setName("BandMetal");
	var contentPane = getContentPane();

	//---- jButtonOK ----
	jButtonOK.setText(bundle.getString("jButtonOK.text"));
	jButtonOK.setName("jButtonOK");

	//---- jButtonCancel ----
	jButtonCancel.setText(bundle.getString("jButtonCancel.text"));
	jButtonCancel.setName("jButtonCancel");

	//---- jLabelName ----
	jLabelName.setText(bundle.getString("jLabelName.text"));
	jLabelName.setName("jLabelName");

	//---- jTextFieldName ----
	jTextFieldName.setName("jTextFieldName");

	//---- jLabelWorkFunction ----
	jLabelWorkFunction.setText(bundle.getString("jLabelWorkFunction.text"));
	jLabelWorkFunction.setName("jLabelWorkFunction");

	//---- jTextFieldWorkFunction ----
	jTextFieldWorkFunction.setName("jTextFieldWorkFunction");

	//---- jButtonPlotColor ----
	jButtonPlotColor.setText(bundle.getString("jButtonPlotColor.text"));
	jButtonPlotColor.setActionCommand(bundle.getString("jButtonPlotColor.actionCommand"));
	jButtonPlotColor.setName("jButtonPlotColor");

	//---- jLabelNotes ----
	jLabelNotes.setText(bundle.getString("jLabelNotes.text"));
	jLabelNotes.setName("jLabelNotes");

	//======== jScrollPane1 ========
	{
	    jScrollPane1.setName("jScrollPane1");

	    //---- jTextAreaNotes ----
	    jTextAreaNotes.setColumns(20);
	    jTextAreaNotes.setLineWrap(true);
	    jTextAreaNotes.setRows(5);
	    jTextAreaNotes.setWrapStyleWord(true);
	    jTextAreaNotes.setName("jTextAreaNotes");
	    jScrollPane1.setViewportView(jTextAreaNotes);
	}

	//======== jPanelPlotColor ========
	{
	    jPanelPlotColor.setName("jPanelPlotColor");

	    GroupLayout jPanelPlotColorLayout = new GroupLayout(jPanelPlotColor);
	    jPanelPlotColor.setLayout(jPanelPlotColorLayout);
	    jPanelPlotColorLayout.setHorizontalGroup(
		jPanelPlotColorLayout.createParallelGroup()
		    .addGap(0, 53, Short.MAX_VALUE)
	    );
	    jPanelPlotColorLayout.setVerticalGroup(
		jPanelPlotColorLayout.createParallelGroup()
		    .addGap(0, 23, Short.MAX_VALUE)
	    );
	}

	GroupLayout contentPaneLayout = new GroupLayout(contentPane);
	contentPane.setLayout(contentPaneLayout);
	contentPaneLayout.setHorizontalGroup(
	    contentPaneLayout.createParallelGroup()
		.addGroup(contentPaneLayout.createSequentialGroup()
		    .addContainerGap()
		    .addGroup(contentPaneLayout.createParallelGroup()
			.addGroup(contentPaneLayout.createSequentialGroup()
			    .addGroup(contentPaneLayout.createParallelGroup()
				.addComponent(jLabelNotes)
				.addGroup(contentPaneLayout.createSequentialGroup()
				    .addComponent(jButtonOK, GroupLayout.PREFERRED_SIZE, 72, GroupLayout.PREFERRED_SIZE)
				    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
				    .addComponent(jButtonCancel)
				    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
				    .addComponent(jButtonPlotColor)))
			    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
			    .addComponent(jPanelPlotColor, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
			.addComponent(jScrollPane1, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
			.addGroup(contentPaneLayout.createSequentialGroup()
			    .addComponent(jLabelName)
			    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
			    .addComponent(jTextFieldName, GroupLayout.PREFERRED_SIZE, 93, GroupLayout.PREFERRED_SIZE)
			    .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
			    .addComponent(jLabelWorkFunction)
			    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
			    .addComponent(jTextFieldWorkFunction, GroupLayout.PREFERRED_SIZE, 145, GroupLayout.PREFERRED_SIZE)
			    .addGap(162, 162, 162)))
		    .addContainerGap())
	);
	contentPaneLayout.setVerticalGroup(
	    contentPaneLayout.createParallelGroup()
		.addGroup(contentPaneLayout.createSequentialGroup()
		    .addContainerGap()
		    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
			.addComponent(jPanelPlotColor, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
			.addGroup(GroupLayout.Alignment.LEADING, contentPaneLayout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
			    .addComponent(jButtonOK, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
			    .addComponent(jButtonCancel, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
			    .addComponent(jButtonPlotColor, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
		    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
		    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
			.addComponent(jLabelName)
			.addComponent(jTextFieldName, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
			.addComponent(jLabelWorkFunction)
			.addComponent(jTextFieldWorkFunction, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
		    .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
		    .addComponent(jLabelNotes)
		    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
		    .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
		    .addContainerGap())
	);
	pack();
	setLocationRelativeTo(getOwner());

	//---- bindings ----
	bindingGroup = new BindingGroup();
	bindingGroup.addBinding(Bindings.createAutoBinding(UpdateStrategy.READ_WRITE,
	    this, ELProperty.create("${currentRecord.name}"),
	    jTextFieldName, BeanProperty.create("text")));
	bindingGroup.addBinding(Bindings.createAutoBinding(UpdateStrategy.READ_WRITE,
	    this, ELProperty.create("${currentRecord.workFunction}"),
	    jTextFieldWorkFunction, BeanProperty.create("text")));
	bindingGroup.addBinding(Bindings.createAutoBinding(UpdateStrategy.READ_WRITE,
	    this, ELProperty.create("${currentRecord.notes}"),
	    jTextAreaNotes, BeanProperty.create("text")));
	bindingGroup.addBinding(Bindings.createAutoBinding(UpdateStrategy.READ_WRITE,
	    this, ELProperty.create("${currentRecord.fillColor}"),
	    jPanelPlotColor, BeanProperty.create("background")));
	bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BandMetal dialog = new BandMetal(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // Generated using JFormDesigner Educational license - Madi Thompson (madithompson)
    private JButton jButtonOK;
    private JButton jButtonCancel;
    private JLabel jLabelName;
    private JTextField jTextFieldName;
    private JLabel jLabelWorkFunction;
    private JTextField jTextFieldWorkFunction;
    private JButton jButtonPlotColor;
    private JLabel jLabelNotes;
    private JScrollPane jScrollPane1;
    private JTextArea jTextAreaNotes;
    private JPanel jPanelPlotColor;
    private BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

}
