/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BandViewWindow.java
 *
 * Created on Jan 20, 2010, 9:01:40 PM
 */

package band;

import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JRootPane;
import javax.swing.KeyStroke;
import org.jdesktop.application.Action;

/**
 *
 * @author mbaker
 */
public class BandViewWindow extends javax.swing.JDialog {

    /** Creates new form BandViewWindow */
    public BandViewWindow(java.awt.Frame parent, boolean modal) {
        super(parent, modal);

        InputMap iMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        iMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), "escape");
        iMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0), "enter");

        getRootPane().getActionMap().put("escape", new AbstractAction() {
           @Override
           public void actionPerformed(ActionEvent e) {
              dispose();
           }
        });

        getRootPane().getActionMap().put("enter", new AbstractAction() {
           @Override
           public void actionPerformed(ActionEvent e) {
              updateValues();
           }
        });

        initComponents();

        JRootPane rp = this.jButtonOk.getRootPane();
        rp.setDefaultButton(jButtonOk);
        
        loadValues();
    }

    @Action
    public void updateValues() {
       BandApp app = BandApp.getApplication();

       app.setxAutoScale(jCheckBoxXAutoScale.isSelected());
       app.setyAutoScale(jCheckBoxYAutoScale.isSelected());

       app.setxMin(Double.valueOf(jTextFieldXMin.getText()));
       app.setxMax(Double.valueOf(jTextFieldXMax.getText()));
       app.setyMin(Double.valueOf(jTextFieldYMin.getText()));
       app.setyMax(Double.valueOf(jTextFieldYMax.getText()));

       if (app.isxAutoScale()) {
          jTextFieldXMin.setEnabled(false);
          jTextFieldXMax.setEnabled(false);
       }
       else {
          jTextFieldXMin.setEnabled(true);
          jTextFieldXMax.setEnabled(true);
       }

       if (app.isyAutoScale()) {
          jTextFieldYMin.setEnabled(false);
          jTextFieldYMax.setEnabled(false);
       }
       else {
          jTextFieldYMin.setEnabled(true);
          jTextFieldYMax.setEnabled(true);
       }
    }

    private void loadValues() {
       BandApp app = BandApp.getApplication();
       jCheckBoxXAutoScale.setSelected(app.isxAutoScale());
       jCheckBoxYAutoScale.setSelected(app.isyAutoScale());

       jTextFieldXMin.setText(String.valueOf(app.getxMin()));
       jTextFieldXMax.setText(String.valueOf(app.getxMax()));
       jTextFieldYMin.setText(String.valueOf(app.getyMin()));
       jTextFieldYMax.setText(String.valueOf(app.getyMax()));
       
       if (app.isxAutoScale()) {
          jTextFieldXMin.setEnabled(false);
          jTextFieldXMax.setEnabled(false);
       }
       else {
          jTextFieldXMin.setEnabled(true);
          jTextFieldXMax.setEnabled(true);
       }

       if (app.isyAutoScale()) {
          jTextFieldYMin.setEnabled(false);
          jTextFieldYMax.setEnabled(false);
       }
       else {
          jTextFieldYMin.setEnabled(true);
          jTextFieldYMax.setEnabled(true);
       }
    }

    @Action
    public void closeWindowBox() {
       updateValues();

       dispose();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelX = new javax.swing.JLabel();
        jTextFieldXMin = new javax.swing.JTextField();
        jTextFieldXMax = new javax.swing.JTextField();
        jCheckBoxXAutoScale = new javax.swing.JCheckBox();
        jLabelY = new javax.swing.JLabel();
        jTextFieldYMin = new javax.swing.JTextField();
        jTextFieldYMax = new javax.swing.JTextField();
        jCheckBoxYAutoScale = new javax.swing.JCheckBox();
        jButtonOk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(band.BandApp.class).getContext().getResourceMap(BandViewWindow.class);
        setTitle(resourceMap.getString("BandViewWindow.title")); // NOI18N
        setModal(true);
        setName("BandViewWindow"); // NOI18N
        setResizable(false);

        jLabelX.setFont(new Font("Tahoma", Font.PLAIN, 12));
        jLabelX.setText(resourceMap.getString("jLabelX.text")); // NOI18N
        jLabelX.setName("jLabelX"); // NOI18N

        jTextFieldXMin.setFont(new Font("Tahoma", Font.PLAIN, 12));
        jTextFieldXMin.setText(resourceMap.getString("jTextFieldXMin.text")); // NOI18N
        jTextFieldXMin.setName("jTextFieldXMin"); // NOI18N

        jTextFieldXMax.setFont(new Font("Tahoma", Font.PLAIN, 12));
        jTextFieldXMax.setText(resourceMap.getString("jTextFieldXMax.text")); // NOI18N
        jTextFieldXMax.setName("jTextFieldXMax"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(band.BandApp.class).getContext().getActionMap(BandViewWindow.class, this);
        jCheckBoxXAutoScale.setAction(actionMap.get("updateValues")); // NOI18N
        jCheckBoxXAutoScale.setFont(new Font("Tahoma", Font.PLAIN, 12));
        jCheckBoxXAutoScale.setText(resourceMap.getString("jCheckBoxXAutoScale.text")); // NOI18N
        jCheckBoxXAutoScale.setName("jCheckBoxXAutoScale"); // NOI18N

        jLabelY.setFont(new Font("Tahoma", Font.PLAIN, 12));
        jLabelY.setText(resourceMap.getString("jLabelY.text")); // NOI18N
        jLabelY.setName("jLabelY"); // NOI18N

        jTextFieldYMin.setFont(new Font("Tahoma", Font.PLAIN, 12));
        jTextFieldYMin.setText(resourceMap.getString("jTextFieldYMin.text")); // NOI18N
        jTextFieldYMin.setName("jTextFieldYMin"); // NOI18N

        jTextFieldYMax.setFont(new Font("Tahoma", Font.PLAIN, 12));
        jTextFieldYMax.setText(resourceMap.getString("jTextFieldYMax.text")); // NOI18N
        jTextFieldYMax.setName("jTextFieldYMax"); // NOI18N

        jCheckBoxYAutoScale.setAction(actionMap.get("updateValues")); // NOI18N
        jCheckBoxYAutoScale.setFont(new Font("Tahoma", Font.PLAIN, 12));
        jCheckBoxYAutoScale.setText(resourceMap.getString("jCheckBoxYAutoScale.text")); // NOI18N
        jCheckBoxYAutoScale.setName("jCheckBoxYAutoScale"); // NOI18N

        jButtonOk.setAction(actionMap.get("closeWindowBox")); // NOI18N
        jButtonOk.setFont(new Font("Tahoma", Font.PLAIN, 12));
        jButtonOk.setText(resourceMap.getString("jButtonOk.text")); // NOI18N
        jButtonOk.setActionCommand(resourceMap.getString("jButtonOk.actionCommand")); // NOI18N
        jButtonOk.setName("jButtonOk"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelX)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldXMin, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxXAutoScale)
                            .addComponent(jTextFieldXMax, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextFieldYMin, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelY, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jButtonOk, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxYAutoScale)
                            .addComponent(jTextFieldYMax))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelX)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldXMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldXMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBoxXAutoScale))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabelY)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldYMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldYMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBoxYAutoScale))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jButtonOk)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BandViewWindow dialog = new BandViewWindow(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonOk;
    private javax.swing.JCheckBox jCheckBoxXAutoScale;
    private javax.swing.JCheckBox jCheckBoxYAutoScale;
    private javax.swing.JLabel jLabelX;
    private javax.swing.JLabel jLabelY;
    private javax.swing.JTextField jTextFieldXMax;
    private javax.swing.JTextField jTextFieldXMin;
    private javax.swing.JTextField jTextFieldYMax;
    private javax.swing.JTextField jTextFieldYMin;
    // End of variables declaration//GEN-END:variables

}
