/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BandViewDielectrics.java
 *
 * Created on Jan 21, 2010, 9:13:51 PM
 */

package band;

import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.util.*;
import java.util.List;
import javax.swing.*;
import javax.swing.AbstractAction;
import javax.swing.GroupLayout;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.KeyStroke;
import javax.swing.LayoutStyle;
import org.jdesktop.application.Action;
import org.jdesktop.beansbinding.*;
import org.jdesktop.beansbinding.AutoBinding.UpdateStrategy;
import org.jdesktop.observablecollections.ObservableCollections;
import org.jdesktop.observablecollections.ObservableList;
import org.jdesktop.swingbinding.*;

/**
 *
 * @author mbaker
 */
public class BandPickSemiconductor extends MaterialPick {
    protected ObservableList<Material> listSemiconductor = ObservableCollections.observableList(BandApp.getApplication().getListSemiconductor());
    public static final String PROP_LISTSEMICONDUCTOR = "listSemiconductor";
    private Semiconductor newSemiconductor;
    private boolean confirmed;
    private double thickness;

    /** Creates new form BandViewDielectrics */
    public BandPickSemiconductor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);

        InputMap iMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        iMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), "escape");
        iMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0), "enter");

        getRootPane().getActionMap().put("escape", new AbstractAction() {
           @Override
           public void actionPerformed(ActionEvent e) {
              dispose();
           }
        });

        getRootPane().getActionMap().put("enter", new AbstractAction() {
           @Override
           public void actionPerformed(ActionEvent e) {
              dispose();
           }
        });

        confirmed = false;

        initComponents();
    }

    public void setReplace(double thickness) {
        this.thickness = thickness;
        if (thickness > 0) {
           jButtonAdd.setText("Replace");
        }
        else {
            jButtonAdd.setText("Add");
        }
    }

    public List<Material> getSemiconductors() {
       return listSemiconductor;
    }
    
    @Action
    public void closeSemiconductorBox() {
       dispose();
    }

    @Override
    public Material getNewMaterial() {
       return newSemiconductor;
    }

    @Override
    public boolean isConfirmed() {
       return confirmed;
    }

    @Action
    public void addRecord() {
      int selectedRow = jTableSemiconductors.getSelectedRow();
      newSemiconductor = (Semiconductor)listSemiconductor.get(selectedRow).clone();

      if (thickness > 0) {
          newSemiconductor.setDopantConcentration(thickness);
          thickness = 0;
          confirmed = true;
      }
      else {
          JFrame mainFrame = BandApp.getApplication().getMainFrame();
          BandMaterialSemiconductor semiconductorBox = new BandMaterialSemiconductor(mainFrame, true);
          semiconductorBox.setCurrentRecord(newSemiconductor);
          semiconductorBox.setVisible(true);

          if (semiconductorBox.isConfirmed()) {
             confirmed = true;
          }
      }

      dispose();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    // Generated using JFormDesigner Educational license - Madi Thompson (madithompson)
    private void initComponents() {
	ResourceBundle bundle = ResourceBundle.getBundle("band.resources.BandPickSemiconductor");
	jButtonAdd = new JButton();
	jButtonClose = new JButton();
	jScrollPaneSemiconductors = new JScrollPane();
	jTableSemiconductors = new JTable();

	//======== this ========
	setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
	setTitle(bundle.getString("BandPickSemiconductor.title"));
	setName("BandPickSemiconductor");
	var contentPane = getContentPane();

	//---- jButtonAdd ----
	jButtonAdd.setText(bundle.getString("jButtonAdd.text"));
	jButtonAdd.setName("jButtonAdd");

	//---- jButtonClose ----
	jButtonClose.setText(bundle.getString("jButtonClose.text"));
	jButtonClose.setName("jButtonClose");

	//======== jScrollPaneSemiconductors ========
	{
	    jScrollPaneSemiconductors.setName("jScrollPaneSemiconductors");

	    //---- jTableSemiconductors ----
	    jTableSemiconductors.setName("jTableSemiconductors");
	    jScrollPaneSemiconductors.setViewportView(jTableSemiconductors);
	}

	GroupLayout contentPaneLayout = new GroupLayout(contentPane);
	contentPane.setLayout(contentPaneLayout);
	contentPaneLayout.setHorizontalGroup(
	    contentPaneLayout.createParallelGroup()
		.addGroup(contentPaneLayout.createSequentialGroup()
		    .addContainerGap()
		    .addGroup(contentPaneLayout.createParallelGroup()
			.addComponent(jButtonAdd)
			.addComponent(jButtonClose))
		    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
		    .addComponent(jScrollPaneSemiconductors, GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
		    .addContainerGap())
	);
	contentPaneLayout.setVerticalGroup(
	    contentPaneLayout.createParallelGroup()
		.addGroup(GroupLayout.Alignment.TRAILING, contentPaneLayout.createSequentialGroup()
		    .addContainerGap()
		    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
			.addComponent(jScrollPaneSemiconductors, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
			.addGroup(contentPaneLayout.createSequentialGroup()
			    .addComponent(jButtonAdd)
			    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 181, Short.MAX_VALUE)
			    .addComponent(jButtonClose)))
		    .addContainerGap())
	);
	pack();
	setLocationRelativeTo(getOwner());

	//---- bindings ----
	bindingGroup = new BindingGroup();
	{
	    var binding = SwingBindings.createJTableBinding(UpdateStrategy.READ_WRITE,
		this, (ELProperty) ELProperty.create("${semiconductors}"), jTableSemiconductors);
	    binding.addColumnBinding(ELProperty.create("${name}"))
		.setColumnName("Name")
		.setColumnClass(String.class);
	    binding.addColumnBinding(ELProperty.create("${dielectricConstant}"))
		.setColumnName("Dielectric Constant")
		.setColumnClass(Double.class);
	    binding.addColumnBinding(ELProperty.create("${bandGap}"))
		.setColumnName("Band Gap")
		.setColumnClass(Double.class);
	    binding.addColumnBinding(ELProperty.create("${electronAffinity}"))
		.setColumnName("Electron Affinity")
		.setColumnClass(Double.class);
	    binding.addColumnBinding(ELProperty.create("${notes}"))
		.setColumnName("Notes")
		.setColumnClass(String.class);
	    bindingGroup.addBinding(binding);
	    binding.bind();
	}
	bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BandPickSemiconductor dialog = new BandPickSemiconductor(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // Generated using JFormDesigner Educational license - Madi Thompson (madithompson)
    private JButton jButtonAdd;
    private JButton jButtonClose;
    private JScrollPane jScrollPaneSemiconductors;
    private JTable jTableSemiconductors;
    private BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

}
