/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BandViewDielectrics.java
 *
 * Created on Jan 21, 2010, 9:13:51 PM
 */

package band;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import javax.swing.AbstractAction;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import org.jdesktop.application.Action;
import org.jdesktop.observablecollections.ObservableCollections;
import org.jdesktop.observablecollections.ObservableList;

/**
 *
 * @author mbaker
 */
public class BandViewMetals extends javax.swing.JDialog {

   
   protected ObservableList<Material> listMetal = ObservableCollections.observableList(BandApp.getApplication().getListMetal());
   public static final String PROP_LISTMETAL = "listMetal";

   /** Creates new form BandViewDielectrics */
    public BandViewMetals(java.awt.Frame parent, boolean modal) {
        super(parent, modal);

        InputMap iMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        iMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), "escape");
        iMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0), "enter");

        getRootPane().getActionMap().put("escape", new AbstractAction() {
           @Override
           public void actionPerformed(ActionEvent e) {
              dispose();
           }
        });

        getRootPane().getActionMap().put("enter", new AbstractAction() {
           @Override
           public void actionPerformed(ActionEvent e) {
              dispose();
           }
        });

        initComponents();
    }

    public List<Material> getMetals() {
       return listMetal;
    }

    @Action
    public void closeMetalsBox() {
       dispose();
    }

    public void showMaterialMetal() {
       BandMetal metalBox = null;
       JFrame mainFrame = BandApp.getApplication().getMainFrame();
       metalBox = new BandMetal(mainFrame,true);
       metalBox.setLocationRelativeTo(this);
       
       BandApp.getApplication().show(metalBox);
    }

    @Action
    public void newRecord() {
       BandMetal metalBox = null;
       Metal newMetal = new Metal();
       newMetal.fillColor = Color.BLACK;

       JFrame mainFrame = BandApp.getApplication().getMainFrame();
       metalBox = new BandMetal(mainFrame,true);
       metalBox.setLocationRelativeTo(this);

       metalBox.setCurrentRecord(newMetal);
       metalBox.setAlwaysOnTop(true);
       metalBox.setVisible(true);

       if (metalBox.isConfirmed()) {
          listMetal.add(newMetal);
       }
       
       Collections.sort(listMetal);
    }
    
    @Action
    public void editRecord() {
       int selectedRow = jTableMetals.getSelectedRow();

       BandMetal metalBox = null;
       
       JFrame mainFrame = BandApp.getApplication().getMainFrame();
       metalBox = new BandMetal(mainFrame,true);
       metalBox.setLocationRelativeTo(this);
       
       Metal tempMetal = (Metal)listMetal.get(selectedRow);
       metalBox.setCurrentRecord((Metal)listMetal.get(selectedRow));
       metalBox.setAlwaysOnTop(true);
       metalBox.setVisible(true);

       if (!metalBox.isConfirmed()) {
          listMetal.remove(selectedRow);
          listMetal.add(selectedRow, tempMetal);
       }
       
       Collections.sort(listMetal);
    }

    @Action
    public void deleteRecord() {
        int n = JOptionPane.showConfirmDialog(null, "Delete the records permanently?", "Warning",
                JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE, null);
        if (n == JOptionPane.YES_OPTION) {
            int[] selected = jTableMetals.getSelectedRows();
            List<Metal> toRemove = new ArrayList<Metal>(selected.length);
            for (int idx = 0; idx < selected.length; idx++) {
                Metal g = (Metal)listMetal.get(jTableMetals.convertRowIndexToModel(selected[idx]));
                toRemove.add(g);
            }
            listMetal.removeAll(toRemove);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jButtonAdd = new javax.swing.JButton();
        jButtonEdit = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jButtonClose = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMetals = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(band.BandApp.class).getContext().getResourceMap(BandViewMetals.class);
        setTitle(resourceMap.getString("BandViewMetals.title")); // NOI18N
        setFont(new Font("Tahoma", Font.PLAIN, 12));
        setName("BandViewMetals"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(band.BandApp.class).getContext().getActionMap(BandViewMetals.class, this);
        jButtonAdd.setAction(actionMap.get("newRecord")); // NOI18N
        jButtonAdd.setFont(new Font("Tahoma", Font.PLAIN, 12));
        jButtonAdd.setText(resourceMap.getString("jButtonAdd.text")); // NOI18N
        jButtonAdd.setName("jButtonAdd"); // NOI18N

        jButtonEdit.setAction(actionMap.get("editRecord")); // NOI18N
        jButtonEdit.setFont(new Font("Tahoma", Font.PLAIN, 12));
        jButtonEdit.setText(resourceMap.getString("jButtonEdit.text")); // NOI18N
        jButtonEdit.setName("jButtonEdit"); // NOI18N

        jButtonDelete.setAction(actionMap.get("deleteRecord")); // NOI18N
        jButtonDelete.setFont(new Font("Tahoma", Font.PLAIN, 12));
        jButtonDelete.setText(resourceMap.getString("jButtonDelete.text")); // NOI18N
        jButtonDelete.setName("jButtonDelete"); // NOI18N

        jButtonClose.setAction(actionMap.get("closeMetalsBox")); // NOI18N
        jButtonClose.setFont(new Font("Tahoma", Font.PLAIN, 12));
        jButtonClose.setText(resourceMap.getString("jButtonClose.text")); // NOI18N
        jButtonClose.setName("jButtonClose"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTableMetals.setFont(new Font("Tahoma", Font.PLAIN, 12));
        jTableMetals.setName("jTableMetals"); // NOI18N

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${metals}");
        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, jTableMetals);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${name}"));
        columnBinding.setColumnName("Name");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${workFunction}"));
        columnBinding.setColumnName("Work Function");
        columnBinding.setColumnClass(Double.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${notes}"));
        columnBinding.setColumnName("Notes");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jTableMetals.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMetalsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableMetals);
        jTableMetals.getColumnModel().getColumn(0).setHeaderValue(resourceMap.getString("jTableMetals.columnModel.title0")); // NOI18N
        jTableMetals.getColumnModel().getColumn(1).setHeaderValue(resourceMap.getString("jTableMetals.columnModel.title1")); // NOI18N
        jTableMetals.getColumnModel().getColumn(2).setHeaderValue(resourceMap.getString("jTableMetals.columnModel.title2")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAdd)
                    .addComponent(jButtonEdit)
                    .addComponent(jButtonDelete)
                    .addComponent(jButtonClose))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                        .addComponent(jButtonClose)))
                .addContainerGap())
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableMetalsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMetalsMouseClicked
      if (evt.getClickCount() == 2) {
         editRecord();
      }
    }//GEN-LAST:event_jTableMetalsMouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BandViewMetals dialog = new BandViewMetals(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableMetals;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
