/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BandViewDielectrics.java
 *
 * Created on Jan 21, 2010, 9:13:51 PM
 */

package band;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import javax.swing.AbstractAction;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import org.jdesktop.application.Action;
import org.jdesktop.observablecollections.ObservableCollections;
import org.jdesktop.observablecollections.ObservableList;

/**
 *
 * @author mbaker
 */
public class BandViewDielectrics extends javax.swing.JDialog {

    protected ObservableList<Material> listDielectric = ObservableCollections.observableList(BandApp.getApplication().getListDielectric());
    public static final String PROP_LISTDIELECTRIC = "listDielectric";

    /** Creates new form BandViewDielectrics */
    public BandViewDielectrics(java.awt.Frame parent, boolean modal) {
        super(parent, modal);

        InputMap iMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        iMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), "escape");
        iMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0), "enter");

        getRootPane().getActionMap().put("escape", new AbstractAction() {
           @Override
           public void actionPerformed(ActionEvent e) {
              dispose();
           }
        });

        getRootPane().getActionMap().put("enter", new AbstractAction() {
           @Override
           public void actionPerformed(ActionEvent e) {
              dispose();
           }
        });

        initComponents();
    }

    @Action
    public void closeDielectricsBox() {
       dispose();
    }

    public List<Material> getDielectrics() {
       return listDielectric;
    }

    public void showMaterialDielectric() {
       BandDielectric dielectricBox = null;

       
       JFrame mainFrame = BandApp.getApplication().getMainFrame();
       dielectricBox = new BandDielectric(mainFrame,true);
       dielectricBox.setLocationRelativeTo(this);

       BandApp.getApplication().show(dielectricBox);
    }

    @Action
    public void newRecord() {
       BandDielectric dielectricBox = null;
       Dielectric newDielectric = new Dielectric();
       newDielectric.fillColor = Color.BLACK;

       JFrame mainFrame = BandApp.getApplication().getMainFrame();
       dielectricBox = new BandDielectric(mainFrame,true);
       dielectricBox.setLocationRelativeTo(this);
       dielectricBox.setCurrentRecord(newDielectric);
       dielectricBox.setVisible(true);

       if (dielectricBox.isConfirmed()) {
          listDielectric.add(newDielectric);
       }
       
       Collections.sort(listDielectric);
    }

    @Action
    public void editRecord() {
       int selectedRow = jTableDielectrics.getSelectedRow();

       BandDielectric dielectricBox = null;

       JFrame mainFrame = BandApp.getApplication().getMainFrame();
       dielectricBox = new BandDielectric(mainFrame,true);
       dielectricBox.setLocationRelativeTo(this);
       
       Dielectric tempDielectric = (Dielectric)listDielectric.get(selectedRow);
       dielectricBox.setCurrentRecord(tempDielectric);
       dielectricBox.setVisible(true);

       if (dielectricBox.isConfirmed()) {
          listDielectric.remove(selectedRow);
          listDielectric.add(selectedRow, tempDielectric);
       }
       
       Collections.sort(listDielectric);
    }

    @Action
    public void deleteRecord() {
        int n = JOptionPane.showConfirmDialog(null, "Delete the records permanently?", "Warning",
                JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE, null);
        if (n == JOptionPane.YES_OPTION) {
            int[] selected = jTableDielectrics.getSelectedRows();
            List<Dielectric> toRemove = new ArrayList<Dielectric>(selected.length);
            for (int idx = 0; idx < selected.length; idx++) {
                Dielectric g = (Dielectric)listDielectric.get(jTableDielectrics.convertRowIndexToModel(selected[idx]));
                toRemove.add(g);
            }
            listDielectric.removeAll(toRemove);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {
      bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

      jButtonAdd = new javax.swing.JButton();
      jButtonEdit = new javax.swing.JButton();
      jButtonDelete = new javax.swing.JButton();
      jButtonClose = new javax.swing.JButton();
      jScrollPane1 = new javax.swing.JScrollPane();
      jTableDielectrics = new javax.swing.JTable();

      setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
      org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(band.BandApp.class).getContext().getResourceMap(BandViewDielectrics.class);
      setTitle(resourceMap.getString("BandViewDielectrics.title")); // NOI18N
      setName("BandViewDielectrics"); // NOI18N

      javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(band.BandApp.class).getContext().getActionMap(BandViewDielectrics.class, this);
      jButtonAdd.setAction(actionMap.get("newRecord")); // NOI18N
      jButtonAdd.setText(resourceMap.getString("jButtonAdd.text")); // NOI18N
      jButtonAdd.setName("jButtonAdd"); // NOI18N

      jButtonEdit.setAction(actionMap.get("editRecord")); // NOI18N
      jButtonEdit.setText(resourceMap.getString("jButtonEdit.text")); // NOI18N
      jButtonEdit.setName("jButtonEdit"); // NOI18N

      jButtonDelete.setAction(actionMap.get("deleteRecord")); // NOI18N
      jButtonDelete.setText(resourceMap.getString("jButtonDelete.text")); // NOI18N
      jButtonDelete.setName("jButtonDelete"); // NOI18N

      jButtonClose.setAction(actionMap.get("closeDielectricsBox")); // NOI18N
      jButtonClose.setText(resourceMap.getString("jButtonClose.text")); // NOI18N
      jButtonClose.setName("jButtonClose"); // NOI18N

      jScrollPane1.setName("jScrollPane1"); // NOI18N

      jTableDielectrics.setName("jTableDielectrics"); // NOI18N

      org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${dielectrics}");
      org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, jTableDielectrics);
      org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${name}"));
      columnBinding.setColumnName("Name");
      columnBinding.setColumnClass(String.class);
      columnBinding.setEditable(false);
      columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${dielectricConstant}"));
      columnBinding.setColumnName("Dielectric Constant");
      columnBinding.setColumnClass(Double.class);
      columnBinding.setEditable(false);
      columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${bandGap}"));
      columnBinding.setColumnName("Band Gap");
      columnBinding.setColumnClass(Double.class);
      columnBinding.setEditable(false);
      columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${electronAffinity}"));
      columnBinding.setColumnName("Electron Affinity");
      columnBinding.setColumnClass(Double.class);
      columnBinding.setEditable(false);
      columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${notes}"));
      columnBinding.setColumnName("Notes");
      columnBinding.setColumnClass(String.class);
      columnBinding.setEditable(false);
      bindingGroup.addBinding(jTableBinding);
      jTableBinding.bind();
      jTableDielectrics.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseClicked(java.awt.event.MouseEvent evt) {
            jTableDielectricsMouseClicked(evt);
         }
      });
      jScrollPane1.setViewportView(jTableDielectrics);
      jTableDielectrics.getColumnModel().getColumn(0).setHeaderValue(resourceMap.getString("jTableDielectrics.columnModel.title0")); // NOI18N
      jTableDielectrics.getColumnModel().getColumn(1).setHeaderValue(resourceMap.getString("jTableDielectrics.columnModel.title1")); // NOI18N
      jTableDielectrics.getColumnModel().getColumn(2).setHeaderValue(resourceMap.getString("jTableDielectrics.columnModel.title2")); // NOI18N
      jTableDielectrics.getColumnModel().getColumn(3).setHeaderValue(resourceMap.getString("jTableDielectrics.columnModel.title3")); // NOI18N
      jTableDielectrics.getColumnModel().getColumn(4).setHeaderValue(resourceMap.getString("jTableDielectrics.columnModel.title4")); // NOI18N

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jButtonAdd)
               .addComponent(jButtonEdit)
               .addComponent(jButtonDelete)
               .addComponent(jButtonClose))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
               .addGroup(layout.createSequentialGroup()
                  .addComponent(jButtonAdd)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(jButtonEdit)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(jButtonDelete)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                  .addComponent(jButtonClose)))
            .addContainerGap())
      );

      bindingGroup.bind();

      pack();
   }// </editor-fold>//GEN-END:initComponents

    private void jTableDielectricsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDielectricsMouseClicked
       if (evt.getClickCount() == 2) {
         editRecord();
      }
    }//GEN-LAST:event_jTableDielectricsMouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BandViewDielectrics dialog = new BandViewDielectrics(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton jButtonAdd;
   private javax.swing.JButton jButtonClose;
   private javax.swing.JButton jButtonDelete;
   private javax.swing.JButton jButtonEdit;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JTable jTableDielectrics;
   private org.jdesktop.beansbinding.BindingGroup bindingGroup;
   // End of variables declaration//GEN-END:variables
}
