/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BandViewDielectrics.java
 *
 * Created on Jan 21, 2010, 9:13:51 PM
 */

package band;

import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.AbstractAction;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.KeyStroke;
import org.jdesktop.application.Action;
import org.jdesktop.observablecollections.ObservableCollections;
import org.jdesktop.observablecollections.ObservableList;

/**
 *
 * @author mbaker
 */
public class BandPickSemiconductor extends MaterialPick {
    protected ObservableList<Material> listSemiconductor = ObservableCollections.observableList(BandApp.getApplication().getListSemiconductor());
    public static final String PROP_LISTSEMICONDUCTOR = "listSemiconductor";
    private Semiconductor newSemiconductor;
    private boolean confirmed;
    private double thickness;

    /** Creates new form BandViewDielectrics */
    public BandPickSemiconductor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);

        InputMap iMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        iMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), "escape");
        iMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0), "enter");

        getRootPane().getActionMap().put("escape", new AbstractAction() {
           @Override
           public void actionPerformed(ActionEvent e) {
              dispose();
           }
        });

        getRootPane().getActionMap().put("enter", new AbstractAction() {
           @Override
           public void actionPerformed(ActionEvent e) {
              dispose();
           }
        });

        confirmed = false;

        initComponents();
    }

    public void setReplace(double thickness) {
        this.thickness = thickness;
        if (thickness > 0) {
           jButtonAdd.setText("Replace");
        }
        else {
            jButtonAdd.setText("Add");
        }
    }

    public List<Material> getSemiconductors() {
       return listSemiconductor;
    }
    
    @Action
    public void closeSemiconductorBox() {
       dispose();
    }

    @Override
    public Material getNewMaterial() {
       return newSemiconductor;
    }

    @Override
    public boolean isConfirmed() {
       return confirmed;
    }

    @Action
    public void addRecord() {
      int selectedRow = jTableSemiconductors.getSelectedRow();
      newSemiconductor = (Semiconductor)listSemiconductor.get(selectedRow).clone();

      if (thickness > 0) {
          newSemiconductor.setDopantConcentration(thickness);
          thickness = 0;
          confirmed = true;
      }
      else {
          JFrame mainFrame = BandApp.getApplication().getMainFrame();
          BandMaterialSemiconductor semiconductorBox = new BandMaterialSemiconductor(mainFrame, true);
          semiconductorBox.setCurrentRecord(newSemiconductor);
          semiconductorBox.setAlwaysOnTop(true);
          semiconductorBox.setVisible(true);

          if (semiconductorBox.isConfirmed()) {
             confirmed = true;
          }
      }

      dispose();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jButtonAdd = new javax.swing.JButton();
        jButtonClose = new javax.swing.JButton();
        jScrollPaneSemiconductors = new javax.swing.JScrollPane();
        jTableSemiconductors = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(band.BandApp.class).getContext().getResourceMap(BandPickSemiconductor.class);
        setTitle(resourceMap.getString("BandPickSemiconductor.title")); // NOI18N
        setName("BandPickSemiconductor"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(band.BandApp.class).getContext().getActionMap(BandPickSemiconductor.class, this);
        jButtonAdd.setAction(actionMap.get("addRecord")); // NOI18N
        jButtonAdd.setFont(new Font("Tahoma", Font.PLAIN, 12));
        jButtonAdd.setText(resourceMap.getString("jButtonAdd.text")); // NOI18N
        jButtonAdd.setName("jButtonAdd"); // NOI18N

        jButtonClose.setAction(actionMap.get("closeSemiconductorBox")); // NOI18N
        jButtonClose.setFont(new Font("Tahoma", Font.PLAIN, 12));
        jButtonClose.setText(resourceMap.getString("jButtonClose.text")); // NOI18N
        jButtonClose.setName("jButtonClose"); // NOI18N

        jScrollPaneSemiconductors.setName("jScrollPaneSemiconductors"); // NOI18N

        jTableSemiconductors.setFont(new Font("Tahoma", Font.PLAIN, 12));
        jTableSemiconductors.setName("jTableSemiconductors"); // NOI18N

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${semiconductors}");
        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, jTableSemiconductors);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${name}"));
        columnBinding.setColumnName("Name");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${dielectricConstant}"));
        columnBinding.setColumnName("Dielectric Constant");
        columnBinding.setColumnClass(Double.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${bandGap}"));
        columnBinding.setColumnName("Band Gap");
        columnBinding.setColumnClass(Double.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${electronAffinity}"));
        columnBinding.setColumnName("Electron Affinity");
        columnBinding.setColumnClass(Double.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${notes}"));
        columnBinding.setColumnName("Notes");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPaneSemiconductors.setViewportView(jTableSemiconductors);
        jTableSemiconductors.getColumnModel().getColumn(0).setHeaderValue(resourceMap.getString("jTableSemiconductors.columnModel.title0")); // NOI18N
        jTableSemiconductors.getColumnModel().getColumn(1).setHeaderValue(resourceMap.getString("jTableSemiconductors.columnModel.title1")); // NOI18N
        jTableSemiconductors.getColumnModel().getColumn(2).setHeaderValue(resourceMap.getString("jTableSemiconductors.columnModel.title2")); // NOI18N
        jTableSemiconductors.getColumnModel().getColumn(3).setHeaderValue(resourceMap.getString("jTableSemiconductors.columnModel.title3")); // NOI18N
        jTableSemiconductors.getColumnModel().getColumn(4).setHeaderValue(resourceMap.getString("jTableSemiconductors.columnModel.title4")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAdd)
                    .addComponent(jButtonClose))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneSemiconductors, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPaneSemiconductors, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 181, Short.MAX_VALUE)
                        .addComponent(jButtonClose)))
                .addContainerGap())
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BandPickSemiconductor dialog = new BandPickSemiconductor(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonClose;
    private javax.swing.JScrollPane jScrollPaneSemiconductors;
    private javax.swing.JTable jTableSemiconductors;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

}
